// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_overview.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const CreateActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (
    id,
    user_id,
    user_name,
    action,
    entity_type,
    entity_id,
    ip_address,
    user_agent,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, user_id, user_name, action, entity_type, entity_id, ip_address, user_agent, created_at
`

type CreateActivityLogParams struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.NullUUID  `json:"user_id"`
	UserName   sql.NullString `json:"user_name"`
	Action     string         `json:"action"`
	EntityType sql.NullString `json:"entity_type"`
	EntityID   uuid.NullUUID  `json:"entity_id"`
	IpAddress  sql.NullString `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRowContext(ctx, CreateActivityLog,
		arg.ID,
		arg.UserID,
		arg.UserName,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const GetActivePentestersCount = `-- name: GetActivePentestersCount :one
SELECT COUNT(*) as count FROM users WHERE status = 'Active' AND role = 'Pentester'
`

func (q *Queries) GetActivePentestersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetActivePentestersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetActiveStakeholdersCount = `-- name: GetActiveStakeholdersCount :one
SELECT COUNT(*) as count FROM users WHERE status = 'Active' AND role = 'Stakeholder'
`

func (q *Queries) GetActiveStakeholdersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetActiveStakeholdersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetActiveUsersCount = `-- name: GetActiveUsersCount :one
SELECT COUNT(*) as total FROM users WHERE status = 'Active'
`

func (q *Queries) GetActiveUsersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetActiveUsersCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const GetActivityLogsCount = `-- name: GetActivityLogsCount :one
SELECT COUNT(*) as total FROM activity_logs
`

func (q *Queries) GetActivityLogsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetActivityLogsCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const GetCompletedProjectsCount = `-- name: GetCompletedProjectsCount :one
SELECT COUNT(*) as count FROM projects WHERE status = 'Completed'
`

func (q *Queries) GetCompletedProjectsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetCompletedProjectsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetCriticalIssuesCount = `-- name: GetCriticalIssuesCount :one
SELECT COUNT(*) as count FROM vulnerabilities WHERE severity = 'Critical'
`

func (q *Queries) GetCriticalIssuesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetCriticalIssuesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetInProgressProjectsCount = `-- name: GetInProgressProjectsCount :one
SELECT COUNT(*) as count FROM projects WHERE status = 'In Progress'
`

func (q *Queries) GetInProgressProjectsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetInProgressProjectsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetOpenIssuesCount = `-- name: GetOpenIssuesCount :one
SELECT COUNT(*) as count FROM vulnerabilities WHERE status = 'Open'
`

func (q *Queries) GetOpenIssuesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetOpenIssuesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetOpenProjectsCount = `-- name: GetOpenProjectsCount :one
SELECT COUNT(*) as count FROM projects WHERE status = 'Open'
`

func (q *Queries) GetOpenProjectsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetOpenProjectsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetProjectStatusDistribution = `-- name: GetProjectStatusDistribution :many
SELECT 
    status,
    COUNT(*) as count
FROM projects
GROUP BY status
ORDER BY 
    CASE status
        WHEN 'Open' THEN 1
        WHEN 'In Progress' THEN 2
        WHEN 'Completed' THEN 3
    END
`

type GetProjectStatusDistributionRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetProjectStatusDistribution(ctx context.Context) ([]GetProjectStatusDistributionRow, error) {
	rows, err := q.db.QueryContext(ctx, GetProjectStatusDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectStatusDistributionRow{}
	for rows.Next() {
		var i GetProjectStatusDistributionRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRecentActivityLogs = `-- name: GetRecentActivityLogs :many
SELECT 
    id,
    user_id,
    user_name,
    action,
    entity_type,
    entity_id,
    ip_address,
    user_agent,
    created_at
FROM activity_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetRecentActivityLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRecentActivityLogs(ctx context.Context, arg GetRecentActivityLogsParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, GetRecentActivityLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTop5DomainsByVulnerabilities = `-- name: GetTop5DomainsByVulnerabilities :many
SELECT
    COALESCE(d.domain_name, 'Unknown') as domain,
    COUNT(*) as vulnerability_count
FROM vulnerabilities v
LEFT JOIN domains d ON v.domain_id = d.id
WHERE v.domain_id IS NOT NULL
GROUP BY d.domain_name
ORDER BY vulnerability_count DESC
LIMIT 5
`

type GetTop5DomainsByVulnerabilitiesRow struct {
	Domain             string `json:"domain"`
	VulnerabilityCount int64  `json:"vulnerability_count"`
}

func (q *Queries) GetTop5DomainsByVulnerabilities(ctx context.Context) ([]GetTop5DomainsByVulnerabilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, GetTop5DomainsByVulnerabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTop5DomainsByVulnerabilitiesRow{}
	for rows.Next() {
		var i GetTop5DomainsByVulnerabilitiesRow
		if err := rows.Scan(&i.Domain, &i.VulnerabilityCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTotalProjectsCount = `-- name: GetTotalProjectsCount :one
SELECT COUNT(*) as total FROM projects
`

func (q *Queries) GetTotalProjectsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetTotalProjectsCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const GetTotalVulnerabilitiesCount = `-- name: GetTotalVulnerabilitiesCount :one
SELECT COUNT(*) as total FROM vulnerabilities
`

func (q *Queries) GetTotalVulnerabilitiesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetTotalVulnerabilitiesCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const GetVulnerabilitiesBySeverity = `-- name: GetVulnerabilitiesBySeverity :many
SELECT 
    severity,
    COUNT(*) as count
FROM vulnerabilities
GROUP BY severity
ORDER BY 
    CASE severity
        WHEN 'Critical' THEN 1
        WHEN 'High' THEN 2
        WHEN 'Medium' THEN 3
        WHEN 'Low' THEN 4
    END
`

type GetVulnerabilitiesBySeverityRow struct {
	Severity string `json:"severity"`
	Count    int64  `json:"count"`
}

func (q *Queries) GetVulnerabilitiesBySeverity(ctx context.Context) ([]GetVulnerabilitiesBySeverityRow, error) {
	rows, err := q.db.QueryContext(ctx, GetVulnerabilitiesBySeverity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVulnerabilitiesBySeverityRow{}
	for rows.Next() {
		var i GetVulnerabilitiesBySeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
