// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const CreateRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, NOW())
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	TokenHash string        `json:"token_hash"`
	ExpiresAt time.Time     `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, CreateRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const DeleteAllUserRefreshTokens = `-- name: DeleteAllUserRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteAllUserRefreshTokens(ctx context.Context, userID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, DeleteAllUserRefreshTokens, userID)
	return err
}

const DeleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, DeleteExpiredRefreshTokens)
	return err
}

const DeleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, DeleteRefreshToken, tokenHash)
	return err
}

const GetRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, created_at
FROM refresh_tokens
WHERE token_hash = $1 AND expires_at > NOW()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, GetRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const GetUserForAuth = `-- name: GetUserForAuth :one
SELECT id, email, password_hash, full_name, role, is_active, force_password_change,
       failed_login_attempts, last_failed_login, account_locked_until, last_login,
       created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserForAuth(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, GetUserForAuth, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLogin,
		&i.AccountLockedUntil,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const IncrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :exec
UPDATE users
SET failed_login_attempts = failed_login_attempts + 1,
    last_failed_login = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, IncrementFailedLoginAttempts, id)
	return err
}

const LockAccount = `-- name: LockAccount :exec
UPDATE users
SET account_locked_until = $2,
    updated_at = NOW()
WHERE id = $1
`

type LockAccountParams struct {
	ID                 uuid.UUID    `json:"id"`
	AccountLockedUntil sql.NullTime `json:"account_locked_until"`
}

func (q *Queries) LockAccount(ctx context.Context, arg LockAccountParams) error {
	_, err := q.db.ExecContext(ctx, LockAccount, arg.ID, arg.AccountLockedUntil)
	return err
}

const ResetFailedLoginAttempts = `-- name: ResetFailedLoginAttempts :exec
UPDATE users
SET failed_login_attempts = 0,
    last_failed_login = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ResetFailedLoginAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, ResetFailedLoginAttempts, id)
	return err
}

const UnlockAccount = `-- name: UnlockAccount :exec
UPDATE users
SET account_locked_until = NULL,
    failed_login_attempts = 0,
    last_failed_login = NULL,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UnlockAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, UnlockAccount, id)
	return err
}

const UpdateLastLoginTime = `-- name: UpdateLastLoginTime :exec
UPDATE users
SET last_login = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateLastLoginTimeParams struct {
	ID        uuid.UUID    `json:"id"`
	LastLogin sql.NullTime `json:"last_login"`
}

func (q *Queries) UpdateLastLoginTime(ctx context.Context, arg UpdateLastLoginTimeParams) error {
	_, err := q.db.ExecContext(ctx, UpdateLastLoginTime, arg.ID, arg.LastLogin)
	return err
}

const UpdateUserForcePasswordChange = `-- name: UpdateUserForcePasswordChange :exec
UPDATE users
SET force_password_change = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserForcePasswordChangeParams struct {
	ID                  uuid.UUID    `json:"id"`
	ForcePasswordChange sql.NullBool `json:"force_password_change"`
}

func (q *Queries) UpdateUserForcePasswordChange(ctx context.Context, arg UpdateUserForcePasswordChangeParams) error {
	_, err := q.db.ExecContext(ctx, UpdateUserForcePasswordChange, arg.ID, arg.ForcePasswordChange)
	return err
}

const UpdateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, UpdateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
