// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const CountDomains = `-- name: CountDomains :one
SELECT COUNT(DISTINCT d.id) as total
FROM domains d
WHERE d.is_active = true
`

func (q *Queries) CountDomains(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountDomains)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const CreateDomain = `-- name: CreateDomain :one
INSERT INTO domains (
    id,
    domain_name,
    ip_address,
    description,
    risk_score,
    is_active,
    last_scanned,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, domain_name, ip_address, description, risk_score, is_active, last_scanned, created_at, updated_at
`

type CreateDomainParams struct {
	ID          uuid.UUID      `json:"id"`
	DomainName  string         `json:"domain_name"`
	IpAddress   sql.NullString `json:"ip_address"`
	Description sql.NullString `json:"description"`
	RiskScore   sql.NullString `json:"risk_score"`
	IsActive    sql.NullBool   `json:"is_active"`
	LastScanned sql.NullTime   `json:"last_scanned"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, CreateDomain,
		arg.ID,
		arg.DomainName,
		arg.IpAddress,
		arg.Description,
		arg.RiskScore,
		arg.IsActive,
		arg.LastScanned,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.IpAddress,
		&i.Description,
		&i.RiskScore,
		&i.IsActive,
		&i.LastScanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateSecurityMetric = `-- name: CreateSecurityMetric :one
INSERT INTO security_metrics (
    id,
    domain_id,
    metric_name,
    metric_value,
    measured_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, domain_id, metric_name, metric_value, measured_at, created_at
`

type CreateSecurityMetricParams struct {
	ID          uuid.UUID      `json:"id"`
	DomainID    uuid.NullUUID  `json:"domain_id"`
	MetricName  string         `json:"metric_name"`
	MetricValue sql.NullString `json:"metric_value"`
	MeasuredAt  sql.NullTime   `json:"measured_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateSecurityMetric(ctx context.Context, arg CreateSecurityMetricParams) (SecurityMetric, error) {
	row := q.db.QueryRowContext(ctx, CreateSecurityMetric,
		arg.ID,
		arg.DomainID,
		arg.MetricName,
		arg.MetricValue,
		arg.MeasuredAt,
		arg.CreatedAt,
	)
	var i SecurityMetric
	err := row.Scan(
		&i.ID,
		&i.DomainID,
		&i.MetricName,
		&i.MetricValue,
		&i.MeasuredAt,
		&i.CreatedAt,
	)
	return i, err
}

const DeleteDomain = `-- name: DeleteDomain :exec
UPDATE domains
SET is_active = false, updated_at = $2
WHERE id = $1
`

type DeleteDomainParams struct {
	ID        uuid.UUID    `json:"id"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) error {
	_, err := q.db.ExecContext(ctx, DeleteDomain, arg.ID, arg.UpdatedAt)
	return err
}

const GetDomainByID = `-- name: GetDomainByID :one
SELECT 
    d.id,
    d.domain_name,
    d.ip_address,
    d.description,
    d.risk_score,
    d.is_active,
    d.last_scanned,
    d.created_at,
    d.updated_at
FROM domains d
WHERE d.id = $1 AND d.is_active = true
`

func (q *Queries) GetDomainByID(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRowContext(ctx, GetDomainByID, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.IpAddress,
		&i.Description,
		&i.RiskScore,
		&i.IsActive,
		&i.LastScanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetDomainsStats = `-- name: GetDomainsStats :one
SELECT 
    COUNT(DISTINCT d.id) as total_domains,
    COALESCE(AVG(d.risk_score), 0) as avg_risk_score,
    COALESCE(SUM(CASE WHEN v.severity = 'critical' THEN 1 ELSE 0 END), 0) as critical_issues,
    COALESCE(
        CAST(
            SUM(CASE 
                WHEN v.due_date IS NOT NULL 
                AND v.status IN ('remediated', 'verified') 
                AND v.remediated_date IS NOT NULL 
                AND v.remediated_date <= v.due_date 
                THEN 1 
                ELSE 0 
            END) * 100.0 / NULLIF(SUM(CASE WHEN v.due_date IS NOT NULL THEN 1 ELSE 0 END), 0)
        AS DECIMAL(5,2)), 
        0
    ) as sla_compliance_percent
FROM domains d
LEFT JOIN vulnerabilities v ON d.domain_name = v.domain
WHERE d.is_active = true
`

type GetDomainsStatsRow struct {
	TotalDomains         int64       `json:"total_domains"`
	AvgRiskScore         interface{} `json:"avg_risk_score"`
	CriticalIssues       interface{} `json:"critical_issues"`
	SlaCompliancePercent interface{} `json:"sla_compliance_percent"`
}

func (q *Queries) GetDomainsStats(ctx context.Context) (GetDomainsStatsRow, error) {
	row := q.db.QueryRowContext(ctx, GetDomainsStats)
	var i GetDomainsStatsRow
	err := row.Scan(
		&i.TotalDomains,
		&i.AvgRiskScore,
		&i.CriticalIssues,
		&i.SlaCompliancePercent,
	)
	return i, err
}

const GetSLABreachAnalysis = `-- name: GetSLABreachAnalysis :many
SELECT 
    d.domain_name,
    COALESCE(
        CAST(
            SUM(CASE 
                WHEN v.due_date IS NOT NULL 
                AND v.status IN ('remediated', 'verified') 
                AND v.remediated_date IS NOT NULL 
                AND v.remediated_date <= v.due_date 
                THEN 1 
                ELSE 0 
            END) * 100.0 / NULLIF(SUM(CASE WHEN v.due_date IS NOT NULL THEN 1 ELSE 0 END), 0)
        AS DECIMAL(5,2)), 
        0
    ) as sla_compliance_percent
FROM domains d
LEFT JOIN vulnerabilities v ON d.domain_name = v.domain
WHERE d.is_active = true
GROUP BY d.domain_name
HAVING SUM(CASE WHEN v.due_date IS NOT NULL THEN 1 ELSE 0 END) > 0
ORDER BY sla_compliance_percent ASC, d.domain_name ASC
`

type GetSLABreachAnalysisRow struct {
	DomainName           string      `json:"domain_name"`
	SlaCompliancePercent interface{} `json:"sla_compliance_percent"`
}

func (q *Queries) GetSLABreachAnalysis(ctx context.Context) ([]GetSLABreachAnalysisRow, error) {
	rows, err := q.db.QueryContext(ctx, GetSLABreachAnalysis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSLABreachAnalysisRow{}
	for rows.Next() {
		var i GetSLABreachAnalysisRow
		if err := rows.Scan(&i.DomainName, &i.SlaCompliancePercent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSecurityMetrics = `-- name: GetSecurityMetrics :many
SELECT 
    metric_name,
    COALESCE(AVG(metric_value), 0) as avg_value
FROM security_metrics
WHERE domain_id IN (
    SELECT id FROM domains WHERE is_active = true
)
AND metric_name IN ('authentication', 'authorization', 'input_validation', 'encryption', 'configuration', 'network_security')
GROUP BY metric_name
`

type GetSecurityMetricsRow struct {
	MetricName string      `json:"metric_name"`
	AvgValue   interface{} `json:"avg_value"`
}

func (q *Queries) GetSecurityMetrics(ctx context.Context) ([]GetSecurityMetricsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetSecurityMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSecurityMetricsRow{}
	for rows.Next() {
		var i GetSecurityMetricsRow
		if err := rows.Scan(&i.MetricName, &i.AvgValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListDomains = `-- name: ListDomains :many
SELECT 
    d.id,
    d.domain_name,
    d.ip_address,
    d.description,
    d.risk_score,
    d.is_active,
    d.last_scanned,
    d.created_at,
    d.updated_at,
    COALESCE(COUNT(v.id), 0) as total_vulnerabilities,
    COALESCE(SUM(CASE WHEN v.severity = 'critical' THEN 1 ELSE 0 END), 0) as critical_count,
    COALESCE(SUM(CASE WHEN v.severity = 'high' THEN 1 ELSE 0 END), 0) as high_count,
    COALESCE(SUM(CASE WHEN v.severity = 'medium' THEN 1 ELSE 0 END), 0) as medium_count,
    COALESCE(SUM(CASE WHEN v.severity = 'low' THEN 1 ELSE 0 END), 0) as low_count,
    COALESCE(SUM(CASE WHEN v.status = 'open' THEN 1 ELSE 0 END), 0) as open_issues,
    COALESCE(
        CAST(
            SUM(CASE 
                WHEN v.due_date IS NOT NULL 
                AND v.status IN ('remediated', 'verified') 
                AND v.remediated_date IS NOT NULL 
                AND v.remediated_date <= v.due_date 
                THEN 1 
                ELSE 0 
            END) * 100.0 / NULLIF(SUM(CASE WHEN v.due_date IS NOT NULL THEN 1 ELSE 0 END), 0)
        AS DECIMAL(5,2)), 
        0
    ) as sla_compliance
FROM domains d
LEFT JOIN vulnerabilities v ON d.domain_name = v.domain
WHERE d.is_active = true
GROUP BY d.id, d.domain_name, d.ip_address, d.description, d.risk_score, d.is_active, d.last_scanned, d.created_at, d.updated_at
ORDER BY d.risk_score DESC NULLS LAST, d.domain_name ASC
LIMIT $1 OFFSET $2
`

type ListDomainsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDomainsRow struct {
	ID                   uuid.UUID      `json:"id"`
	DomainName           string         `json:"domain_name"`
	IpAddress            sql.NullString `json:"ip_address"`
	Description          sql.NullString `json:"description"`
	RiskScore            sql.NullString `json:"risk_score"`
	IsActive             sql.NullBool   `json:"is_active"`
	LastScanned          sql.NullTime   `json:"last_scanned"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
	TotalVulnerabilities interface{}    `json:"total_vulnerabilities"`
	CriticalCount        interface{}    `json:"critical_count"`
	HighCount            interface{}    `json:"high_count"`
	MediumCount          interface{}    `json:"medium_count"`
	LowCount             interface{}    `json:"low_count"`
	OpenIssues           interface{}    `json:"open_issues"`
	SlaCompliance        interface{}    `json:"sla_compliance"`
}

func (q *Queries) ListDomains(ctx context.Context, arg ListDomainsParams) ([]ListDomainsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListDomains, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDomainsRow{}
	for rows.Next() {
		var i ListDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.DomainName,
			&i.IpAddress,
			&i.Description,
			&i.RiskScore,
			&i.IsActive,
			&i.LastScanned,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalVulnerabilities,
			&i.CriticalCount,
			&i.HighCount,
			&i.MediumCount,
			&i.LowCount,
			&i.OpenIssues,
			&i.SlaCompliance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateDomain = `-- name: UpdateDomain :one
UPDATE domains
SET 
    domain_name = $2,
    ip_address = $3,
    description = $4,
    risk_score = $5,
    last_scanned = $6,
    updated_at = $7
WHERE id = $1 AND is_active = true
RETURNING id, domain_name, ip_address, description, risk_score, is_active, last_scanned, created_at, updated_at
`

type UpdateDomainParams struct {
	ID          uuid.UUID      `json:"id"`
	DomainName  string         `json:"domain_name"`
	IpAddress   sql.NullString `json:"ip_address"`
	Description sql.NullString `json:"description"`
	RiskScore   sql.NullString `json:"risk_score"`
	LastScanned sql.NullTime   `json:"last_scanned"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, UpdateDomain,
		arg.ID,
		arg.DomainName,
		arg.IpAddress,
		arg.Description,
		arg.RiskScore,
		arg.LastScanned,
		arg.UpdatedAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.DomainName,
		&i.IpAddress,
		&i.Description,
		&i.RiskScore,
		&i.IsActive,
		&i.LastScanned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
