// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ActivityLog struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.NullUUID  `json:"user_id"`
	UserName   sql.NullString `json:"user_name"`
	Action     string         `json:"action"`
	EntityType sql.NullString `json:"entity_type"`
	EntityID   uuid.NullUUID  `json:"entity_id"`
	IpAddress  sql.NullString `json:"ip_address"`
	UserAgent  sql.NullString `json:"user_agent"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Alert struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Message     string         `json:"message"`
	AlertType   sql.NullString `json:"alert_type"`
	Priority    sql.NullString `json:"priority"`
	Source      sql.NullString `json:"source"`
	RecipientID uuid.NullUUID  `json:"recipient_id"`
	SenderID    uuid.NullUUID  `json:"sender_id"`
	IsRead      sql.NullBool   `json:"is_read"`
	IsDismissed sql.NullBool   `json:"is_dismissed"`
	IsResolved  sql.NullBool   `json:"is_resolved"`
	ResolvedBy  uuid.NullUUID  `json:"resolved_by"`
	ResolvedAt  sql.NullTime   `json:"resolved_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Domain struct {
	ID          uuid.UUID      `json:"id"`
	DomainName  string         `json:"domain_name"`
	IpAddress   sql.NullString `json:"ip_address"`
	Description sql.NullString `json:"description"`
	RiskScore   sql.NullString `json:"risk_score"`
	IsActive    sql.NullBool   `json:"is_active"`
	LastScanned sql.NullTime   `json:"last_scanned"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type EvidenceFile struct {
	ID         uuid.UUID      `json:"id"`
	ReportID   uuid.NullUUID  `json:"report_id"`
	FileName   string         `json:"file_name"`
	FilePath   string         `json:"file_path"`
	FileSize   int64          `json:"file_size"`
	FileType   sql.NullString `json:"file_type"`
	UploadedBy uuid.NullUUID  `json:"uploaded_by"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
}

type Notification struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Message     string         `json:"message"`
	SentTo      string         `json:"sent_to"`
	RecipientID uuid.NullUUID  `json:"recipient_id"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	Status      sql.NullString `json:"status"`
	Type        sql.NullString `json:"type"`
	IsRead      sql.NullBool   `json:"is_read"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Project struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Type         string         `json:"type"`
	AssignedTo   uuid.NullUUID  `json:"assigned_to"`
	Deadline     time.Time      `json:"deadline"`
	Scope        sql.NullString `json:"scope"`
	Status       string         `json:"status"`
	CurrentPhase sql.NullString `json:"current_phase"`
	CreatedBy    uuid.NullUUID  `json:"created_by"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type ProjectAsset struct {
	ID        uuid.UUID     `json:"id"`
	ProjectID uuid.NullUUID `json:"project_id"`
	DomainID  uuid.NullUUID `json:"domain_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type ProjectRequirement struct {
	ID              uuid.UUID     `json:"id"`
	ProjectID       uuid.NullUUID `json:"project_id"`
	RequirementText string        `json:"requirement_text"`
	IsCompleted     sql.NullBool  `json:"is_completed"`
	CreatedAt       sql.NullTime  `json:"created_at"`
	UpdatedAt       sql.NullTime  `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	TokenHash string        `json:"token_hash"`
	ExpiresAt time.Time     `json:"expires_at"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Report struct {
	ID               uuid.UUID      `json:"id"`
	ProjectID        uuid.NullUUID  `json:"project_id"`
	Title            string         `json:"title"`
	ReportType       sql.NullString `json:"report_type"`
	FilePath         sql.NullString `json:"file_path"`
	FileSize         sql.NullInt64  `json:"file_size"`
	SubmittedBy      uuid.NullUUID  `json:"submitted_by"`
	Status           sql.NullString `json:"status"`
	ExecutiveSummary sql.NullString `json:"executive_summary"`
	Feedback         sql.NullString `json:"feedback"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type ReportVulnerability struct {
	ID                        uuid.UUID      `json:"id"`
	ReportID                  uuid.NullUUID  `json:"report_id"`
	AssetTarget               string         `json:"asset_target"`
	VulnerabilityTitle        string         `json:"vulnerability_title"`
	Severity                  string         `json:"severity"`
	AttackVector              sql.NullString `json:"attack_vector"`
	VulnerabilityDescription  string         `json:"vulnerability_description"`
	EvidencePoc               sql.NullString `json:"evidence_poc"`
	RemediationRecommendation sql.NullString `json:"remediation_recommendation"`
	CreatedAt                 sql.NullTime   `json:"created_at"`
	UpdatedAt                 sql.NullTime   `json:"updated_at"`
}

type SecurityMetric struct {
	ID          uuid.UUID      `json:"id"`
	DomainID    uuid.NullUUID  `json:"domain_id"`
	MetricName  string         `json:"metric_name"`
	MetricValue sql.NullString `json:"metric_value"`
	MeasuredAt  sql.NullTime   `json:"measured_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Task struct {
	ID          uuid.UUID      `json:"id"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    sql.NullString `json:"priority"`
	AssignedTo  uuid.NullUUID  `json:"assigned_to"`
	Deadline    sql.NullTime   `json:"deadline"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID                  uuid.UUID     `json:"id"`
	Email               string        `json:"email"`
	PasswordHash        string        `json:"password_hash"`
	FullName            string        `json:"full_name"`
	Role                string        `json:"role"`
	IsActive            sql.NullBool  `json:"is_active"`
	ForcePasswordChange sql.NullBool  `json:"force_password_change"`
	FailedLoginAttempts sql.NullInt32 `json:"failed_login_attempts"`
	LastFailedLogin     sql.NullTime  `json:"last_failed_login"`
	AccountLockedUntil  sql.NullTime  `json:"account_locked_until"`
	LastLogin           sql.NullTime  `json:"last_login"`
	CreatedAt           sql.NullTime  `json:"created_at"`
	UpdatedAt           sql.NullTime  `json:"updated_at"`
}

type Vulnerability struct {
	ID               uuid.UUID      `json:"id"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Severity         string         `json:"severity"`
	Domain           string         `json:"domain"`
	Status           string         `json:"status"`
	DiscoveredDate   sql.NullTime   `json:"discovered_date"`
	DueDate          time.Time      `json:"due_date"`
	AssignedTo       sql.NullString `json:"assigned_to"`
	CvssScore        sql.NullString `json:"cvss_score"`
	CweID            sql.NullString `json:"cwe_id"`
	DomainID         uuid.NullUUID  `json:"domain_id"`
	ProjectID        uuid.NullUUID  `json:"project_id"`
	DiscoveredBy     uuid.NullUUID  `json:"discovered_by"`
	RemediationNotes sql.NullString `json:"remediation_notes"`
	RemediatedDate   sql.NullTime   `json:"remediated_date"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}
