// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const CountImportantAlerts = `-- name: CountImportantAlerts :one
SELECT COUNT(*) as total
FROM alerts
WHERE alert_type = 'important_update' AND source = 'pentester'
`

func (q *Queries) CountImportantAlerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountImportantAlerts)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const CountNotifications = `-- name: CountNotifications :one
SELECT COUNT(*) as total
FROM notifications
WHERE created_by = $1
`

func (q *Queries) CountNotifications(ctx context.Context, createdBy uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountNotifications, createdBy)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const CreateAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    id,
    title,
    message,
    alert_type,
    priority,
    source,
    sender_id,
    recipient_id,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, title, message, alert_type, priority, source, recipient_id, sender_id, is_read, is_dismissed, is_resolved, resolved_by, resolved_at, created_at, updated_at
`

type CreateAlertParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Message     string         `json:"message"`
	AlertType   sql.NullString `json:"alert_type"`
	Priority    sql.NullString `json:"priority"`
	Source      sql.NullString `json:"source"`
	SenderID    uuid.NullUUID  `json:"sender_id"`
	RecipientID uuid.NullUUID  `json:"recipient_id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRowContext(ctx, CreateAlert,
		arg.ID,
		arg.Title,
		arg.Message,
		arg.AlertType,
		arg.Priority,
		arg.Source,
		arg.SenderID,
		arg.RecipientID,
		arg.CreatedAt,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.AlertType,
		&i.Priority,
		&i.Source,
		&i.RecipientID,
		&i.SenderID,
		&i.IsRead,
		&i.IsDismissed,
		&i.IsResolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const CreateNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    id,
    title,
    message,
    sent_to,
    recipient_id,
    created_by,
    status,
    type,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, title, message, sent_to, recipient_id, created_by, status, type, is_read, created_at
`

type CreateNotificationParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Message     string         `json:"message"`
	SentTo      string         `json:"sent_to"`
	RecipientID uuid.NullUUID  `json:"recipient_id"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	Status      sql.NullString `json:"status"`
	Type        sql.NullString `json:"type"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, CreateNotification,
		arg.ID,
		arg.Title,
		arg.Message,
		arg.SentTo,
		arg.RecipientID,
		arg.CreatedBy,
		arg.Status,
		arg.Type,
		arg.CreatedAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.SentTo,
		&i.RecipientID,
		&i.CreatedBy,
		&i.Status,
		&i.Type,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const GetAlertByID = `-- name: GetAlertByID :one
SELECT
    a.id,
    a.title,
    a.message,
    a.alert_type,
    a.priority,
    a.source,
    a.sender_id,
    a.is_resolved,
    a.resolved_by,
    a.resolved_at,
    a.created_at,
    a.updated_at,
    u.full_name as pentester_name
FROM alerts a
LEFT JOIN users u ON a.sender_id = u.id
WHERE a.id = $1
`

type GetAlertByIDRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Message       string         `json:"message"`
	AlertType     sql.NullString `json:"alert_type"`
	Priority      sql.NullString `json:"priority"`
	Source        sql.NullString `json:"source"`
	SenderID      uuid.NullUUID  `json:"sender_id"`
	IsResolved    sql.NullBool   `json:"is_resolved"`
	ResolvedBy    uuid.NullUUID  `json:"resolved_by"`
	ResolvedAt    sql.NullTime   `json:"resolved_at"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	PentesterName sql.NullString `json:"pentester_name"`
}

func (q *Queries) GetAlertByID(ctx context.Context, id uuid.UUID) (GetAlertByIDRow, error) {
	row := q.db.QueryRowContext(ctx, GetAlertByID, id)
	var i GetAlertByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.AlertType,
		&i.Priority,
		&i.Source,
		&i.SenderID,
		&i.IsResolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PentesterName,
	)
	return i, err
}

const GetNotificationByID = `-- name: GetNotificationByID :one
SELECT 
    n.id,
    n.title,
    n.message,
    n.sent_to,
    n.recipient_id,
    n.created_by,
    n.status,
    n.type,
    n.is_read,
    n.created_at,
    u.full_name as created_by_name,
    CASE 
        WHEN n.sent_to = 'specific_user' THEN ru.full_name
        ELSE NULL
    END as recipient_name
FROM notifications n
LEFT JOIN users u ON n.created_by = u.id
LEFT JOIN users ru ON n.recipient_id = ru.id
WHERE n.id = $1
`

type GetNotificationByIDRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Message       string         `json:"message"`
	SentTo        string         `json:"sent_to"`
	RecipientID   uuid.NullUUID  `json:"recipient_id"`
	CreatedBy     uuid.UUID      `json:"created_by"`
	Status        sql.NullString `json:"status"`
	Type          sql.NullString `json:"type"`
	IsRead        sql.NullBool   `json:"is_read"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	CreatedByName sql.NullString `json:"created_by_name"`
	RecipientName interface{}    `json:"recipient_name"`
}

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (GetNotificationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, GetNotificationByID, id)
	var i GetNotificationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Message,
		&i.SentTo,
		&i.RecipientID,
		&i.CreatedBy,
		&i.Status,
		&i.Type,
		&i.IsRead,
		&i.CreatedAt,
		&i.CreatedByName,
		&i.RecipientName,
	)
	return i, err
}

const GetTotalNotificationsSent = `-- name: GetTotalNotificationsSent :one
SELECT COUNT(*) as total
FROM notifications
WHERE created_by = $1
`

func (q *Queries) GetTotalNotificationsSent(ctx context.Context, createdBy uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetTotalNotificationsSent, createdBy)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const GetUsersByRole = `-- name: GetUsersByRole :many
SELECT id, email, full_name, role
FROM users
WHERE role = $1 AND is_active = true
`

type GetUsersByRoleRow struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	FullName string    `json:"full_name"`
	Role     string    `json:"role"`
}

func (q *Queries) GetUsersByRole(ctx context.Context, role string) ([]GetUsersByRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, GetUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByRoleRow{}
	for rows.Next() {
		var i GetUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListImportantAlerts = `-- name: ListImportantAlerts :many
SELECT
    a.id,
    a.title,
    a.message,
    a.alert_type,
    a.priority,
    a.source,
    a.sender_id,
    a.is_resolved,
    a.resolved_by,
    a.resolved_at,
    a.created_at,
    a.updated_at,
    u.full_name as pentester_name
FROM alerts a
LEFT JOIN users u ON a.sender_id = u.id
WHERE a.alert_type = 'important_update' AND a.source = 'pentester'
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

type ListImportantAlertsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListImportantAlertsRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Message       string         `json:"message"`
	AlertType     sql.NullString `json:"alert_type"`
	Priority      sql.NullString `json:"priority"`
	Source        sql.NullString `json:"source"`
	SenderID      uuid.NullUUID  `json:"sender_id"`
	IsResolved    sql.NullBool   `json:"is_resolved"`
	ResolvedBy    uuid.NullUUID  `json:"resolved_by"`
	ResolvedAt    sql.NullTime   `json:"resolved_at"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	PentesterName sql.NullString `json:"pentester_name"`
}

func (q *Queries) ListImportantAlerts(ctx context.Context, arg ListImportantAlertsParams) ([]ListImportantAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListImportantAlerts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportantAlertsRow{}
	for rows.Next() {
		var i ListImportantAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.AlertType,
			&i.Priority,
			&i.Source,
			&i.SenderID,
			&i.IsResolved,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PentesterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListNotifications = `-- name: ListNotifications :many
SELECT 
    n.id,
    n.title,
    n.message,
    n.sent_to,
    n.recipient_id,
    n.created_by,
    n.status,
    n.type,
    n.is_read,
    n.created_at,
    u.full_name as created_by_name,
    CASE 
        WHEN n.sent_to = 'specific_user' THEN ru.full_name
        ELSE NULL
    END as recipient_name
FROM notifications n
LEFT JOIN users u ON n.created_by = u.id
LEFT JOIN users ru ON n.recipient_id = ru.id
WHERE n.created_by = $1
ORDER BY n.created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	CreatedBy uuid.UUID `json:"created_by"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListNotificationsRow struct {
	ID            uuid.UUID      `json:"id"`
	Title         string         `json:"title"`
	Message       string         `json:"message"`
	SentTo        string         `json:"sent_to"`
	RecipientID   uuid.NullUUID  `json:"recipient_id"`
	CreatedBy     uuid.UUID      `json:"created_by"`
	Status        sql.NullString `json:"status"`
	Type          sql.NullString `json:"type"`
	IsRead        sql.NullBool   `json:"is_read"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	CreatedByName sql.NullString `json:"created_by_name"`
	RecipientName interface{}    `json:"recipient_name"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListNotifications, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNotificationsRow{}
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.SentTo,
			&i.RecipientID,
			&i.CreatedBy,
			&i.Status,
			&i.Type,
			&i.IsRead,
			&i.CreatedAt,
			&i.CreatedByName,
			&i.RecipientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
