// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const CountProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
`

func (q *Queries) CountProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    name,
    type,
    assigned_to,
    deadline,
    scope,
    status,
    current_phase,
    created_by,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, name, type, assigned_to, deadline, scope, status, current_phase, created_by, created_at, updated_at
`

type CreateProjectParams struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Type         string         `json:"type"`
	AssignedTo   uuid.NullUUID  `json:"assigned_to"`
	Deadline     time.Time      `json:"deadline"`
	Scope        sql.NullString `json:"scope"`
	Status       string         `json:"status"`
	CurrentPhase sql.NullString `json:"current_phase"`
	CreatedBy    uuid.NullUUID  `json:"created_by"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, CreateProject,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.AssignedTo,
		arg.Deadline,
		arg.Scope,
		arg.Status,
		arg.CurrentPhase,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AssignedTo,
		&i.Deadline,
		&i.Scope,
		&i.Status,
		&i.CurrentPhase,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteProject, id)
	return err
}

const GetPentesters = `-- name: GetPentesters :many
SELECT id, full_name, email
FROM users
WHERE role = 'pentester' AND is_active = true
ORDER BY full_name ASC
`

type GetPentestersRow struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
}

func (q *Queries) GetPentesters(ctx context.Context) ([]GetPentestersRow, error) {
	rows, err := q.db.QueryContext(ctx, GetPentesters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPentestersRow{}
	for rows.Next() {
		var i GetPentestersRow
		if err := rows.Scan(&i.ID, &i.FullName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetProjectByID = `-- name: GetProjectByID :one
SELECT id, name, type, assigned_to, deadline, scope, status, current_phase, created_by, created_at, updated_at FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRowContext(ctx, GetProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AssignedTo,
		&i.Deadline,
		&i.Scope,
		&i.Status,
		&i.CurrentPhase,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetProjectByName = `-- name: GetProjectByName :one
SELECT id, name, type, assigned_to, deadline, scope, status, current_phase, created_by, created_at, updated_at FROM projects
WHERE name = $1
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, GetProjectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.AssignedTo,
		&i.Deadline,
		&i.Scope,
		&i.Status,
		&i.CurrentPhase,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetProjectStats = `-- name: GetProjectStats :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'open') as open_count,
    COUNT(*) FILTER (WHERE status = 'in_progress') as in_progress_count,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_count
FROM projects
`

type GetProjectStatsRow struct {
	OpenCount       int64 `json:"open_count"`
	InProgressCount int64 `json:"in_progress_count"`
	CompletedCount  int64 `json:"completed_count"`
}

func (q *Queries) GetProjectStats(ctx context.Context) (GetProjectStatsRow, error) {
	row := q.db.QueryRowContext(ctx, GetProjectStats)
	var i GetProjectStatsRow
	err := row.Scan(&i.OpenCount, &i.InProgressCount, &i.CompletedCount)
	return i, err
}

const GetProjectsByPentester = `-- name: GetProjectsByPentester :many
SELECT 
    p.id, p.name, p.type, p.assigned_to, p.deadline, p.scope, p.status, p.current_phase, p.created_by, p.created_at, p.updated_at,
    u.full_name as assigned_to_name,
    COALESCE(v.vuln_count, 0) as vulnerability_count
FROM projects p
LEFT JOIN users u ON p.assigned_to = u.id
LEFT JOIN (
    SELECT project_id, COUNT(*) as vuln_count
    FROM vulnerabilities
    GROUP BY project_id
) v ON p.id = v.project_id
WHERE p.assigned_to = $1
ORDER BY p.created_at DESC
`

type GetProjectsByPentesterRow struct {
	ID                 uuid.UUID      `json:"id"`
	Name               string         `json:"name"`
	Type               string         `json:"type"`
	AssignedTo         uuid.NullUUID  `json:"assigned_to"`
	Deadline           time.Time      `json:"deadline"`
	Scope              sql.NullString `json:"scope"`
	Status             string         `json:"status"`
	CurrentPhase       sql.NullString `json:"current_phase"`
	CreatedBy          uuid.NullUUID  `json:"created_by"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	AssignedToName     sql.NullString `json:"assigned_to_name"`
	VulnerabilityCount int64          `json:"vulnerability_count"`
}

func (q *Queries) GetProjectsByPentester(ctx context.Context, assignedTo uuid.NullUUID) ([]GetProjectsByPentesterRow, error) {
	rows, err := q.db.QueryContext(ctx, GetProjectsByPentester, assignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectsByPentesterRow{}
	for rows.Next() {
		var i GetProjectsByPentesterRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.AssignedTo,
			&i.Deadline,
			&i.Scope,
			&i.Status,
			&i.CurrentPhase,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignedToName,
			&i.VulnerabilityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListProjects = `-- name: ListProjects :many
SELECT 
    p.id, p.name, p.type, p.assigned_to, p.deadline, p.scope, p.status, p.current_phase, p.created_by, p.created_at, p.updated_at,
    u.full_name as assigned_to_name,
    COALESCE(v.vuln_count, 0) as vulnerability_count
FROM projects p
LEFT JOIN users u ON p.assigned_to = u.id
LEFT JOIN (
    SELECT project_id, COUNT(*) as vuln_count
    FROM vulnerabilities
    GROUP BY project_id
) v ON p.id = v.project_id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProjectsRow struct {
	ID                 uuid.UUID      `json:"id"`
	Name               string         `json:"name"`
	Type               string         `json:"type"`
	AssignedTo         uuid.NullUUID  `json:"assigned_to"`
	Deadline           time.Time      `json:"deadline"`
	Scope              sql.NullString `json:"scope"`
	Status             string         `json:"status"`
	CurrentPhase       sql.NullString `json:"current_phase"`
	CreatedBy          uuid.NullUUID  `json:"created_by"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	AssignedToName     sql.NullString `json:"assigned_to_name"`
	VulnerabilityCount int64          `json:"vulnerability_count"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.AssignedTo,
			&i.Deadline,
			&i.Scope,
			&i.Status,
			&i.CurrentPhase,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignedToName,
			&i.VulnerabilityCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateProjectStatus = `-- name: UpdateProjectStatus :exec
UPDATE projects 
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateProjectStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateProjectStatus, arg.ID, arg.Status)
	return err
}
