// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CountDomains(ctx context.Context) (int64, error)
	CountImportantAlerts(ctx context.Context) (int64, error)
	CountInactiveUsers(ctx context.Context) (int64, error)
	CountNotifications(ctx context.Context, createdBy uuid.UUID) (int64, error)
	// UC34: Count total alerts for pentester (with filters)
	CountPentesterAlerts(ctx context.Context, arg CountPentesterAlertsParams) (int64, error)
	// Count total assigned projects for pentester
	CountPentesterAssignedProjects(ctx context.Context, assignedTo uuid.NullUUID) (int64, error)
	// UC27: Count total submitted reports by pentester
	CountPentesterSubmittedReports(ctx context.Context, submittedBy uuid.NullUUID) (int64, error)
	CountProjects(ctx context.Context) (int64, error)
	CountSearchAndFilterVulnerabilities(ctx context.Context, arg CountSearchAndFilterVulnerabilitiesParams) (int64, error)
	CountTasksByProject(ctx context.Context, projectID uuid.NullUUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context, arg CountUsersByRoleParams) (int64, error)
	CountVulnerabilities(ctx context.Context) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	// UC38: Create alert to send to admin
	CreateAlertToAdmin(ctx context.Context, arg CreateAlertToAdminParams) (CreateAlertToAdminRow, error)
	CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// UC23: Create a new report
	CreatePentesterReport(ctx context.Context, arg CreatePentesterReportParams) (CreatePentesterReportRow, error)
	// UC17: Create New Task
	CreatePentesterTask(ctx context.Context, arg CreatePentesterTaskParams) (Task, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// UC23: Create vulnerability details for a report
	CreateReportVulnerability(ctx context.Context, arg CreateReportVulnerabilityParams) (ReportVulnerability, error)
	CreateSecurityMetric(ctx context.Context, arg CreateSecurityMetricParams) (SecurityMetric, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVulnerability(ctx context.Context, arg CreateVulnerabilityParams) (Vulnerability, error)
	DeleteAllUserRefreshTokens(ctx context.Context, userID uuid.NullUUID) error
	DeleteDomain(ctx context.Context, arg DeleteDomainParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	// UC20: Delete Task
	DeletePentesterTask(ctx context.Context, id uuid.UUID) error
	DeleteProject(ctx context.Context, id uuid.UUID) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteTask(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteVulnerability(ctx context.Context, id uuid.UUID) error
	// UC37: Dismiss alert
	DismissAlert(ctx context.Context, arg DismissAlertParams) error
	// ============================================================================
	// UC24: Export vulnerabilities to CSV (all matching filters)
	// ============================================================================
	ExportStakeholderVulnerabilities(ctx context.Context, arg ExportStakeholderVulnerabilitiesParams) ([]ExportStakeholderVulnerabilitiesRow, error)
	ExportVulnerabilities(ctx context.Context, arg ExportVulnerabilitiesParams) ([]ExportVulnerabilitiesRow, error)
	GetActivePentestersCount(ctx context.Context) (int64, error)
	GetActiveProjectsCounts(ctx context.Context) (GetActiveProjectsCountsRow, error)
	GetActiveStakeholdersCount(ctx context.Context) (int64, error)
	GetActiveUsersCount(ctx context.Context) (int64, error)
	GetActivityLogsCount(ctx context.Context) (int64, error)
	// Get admin user ID (for sending alerts to admin)
	GetAdminUserID(ctx context.Context) (uuid.UUID, error)
	GetAlertByID(ctx context.Context, id uuid.UUID) (GetAlertByIDRow, error)
	// Get single alert details
	GetAlertDetails(ctx context.Context, arg GetAlertDetailsParams) (GetAlertDetailsRow, error)
	GetAssetVulnerabilityCounts(ctx context.Context) ([]GetAssetVulnerabilityCountsRow, error)
	GetCompletedProjectsCount(ctx context.Context) (int64, error)
	GetCriticalIssuesCount(ctx context.Context) (int64, error)
	GetDomainByID(ctx context.Context, id uuid.UUID) (Domain, error)
	GetDomainsStats(ctx context.Context) (GetDomainsStatsRow, error)
	GetInProgressProjectsCount(ctx context.Context) (int64, error)
	GetNotificationByID(ctx context.Context, id uuid.UUID) (GetNotificationByIDRow, error)
	GetOpenIssuesCount(ctx context.Context) (int64, error)
	GetOpenProjectsCount(ctx context.Context) (int64, error)
	GetOpenVulnerabilitiesCurrentMonth(ctx context.Context) (int64, error)
	GetOpenVulnerabilitiesLastMonth(ctx context.Context) (int64, error)
	GetPentesterActiveProjects(ctx context.Context, arg GetPentesterActiveProjectsParams) ([]GetPentesterActiveProjectsRow, error)
	// Pentester Overview Queries
	GetPentesterActiveProjectsCount(ctx context.Context, assignedTo uuid.NullUUID) (int64, error)
	// ============================================================================
	// PENTESTER ALERTS QUERIES
	// ============================================================================
	// UC33: Get alert statistics for pentester
	GetPentesterAlertStats(ctx context.Context, recipientID uuid.NullUUID) (GetPentesterAlertStatsRow, error)
	// UC34: Get all alerts for pentester (with pagination and filters)
	GetPentesterAlerts(ctx context.Context, arg GetPentesterAlertsParams) ([]GetPentesterAlertsRow, error)
	// UC9: Fetch and Display Assigned Projects List
	GetPentesterAssignedProjects(ctx context.Context, assignedTo uuid.NullUUID) ([]GetPentesterAssignedProjectsRow, error)
	GetPentesterAverageAssessmentTime(ctx context.Context, assignedTo uuid.NullUUID) (interface{}, error)
	GetPentesterCriticalHighVulnsCount(ctx context.Context, discoveredBy uuid.NullUUID) (int64, error)
	// UC10: Get Project Progress (used in UC9 query above)
	// This is handled by the subquery in GetPentesterAssignedProjects
	// UC11: Get Project Scope Description (part of GetPentesterAssignedProjects)
	// UC14: Get Project Current Phase (part of GetPentesterAssignedProjects)
	// Get single project details for pentester
	GetPentesterProjectByID(ctx context.Context, arg GetPentesterProjectByIDParams) (GetPentesterProjectByIDRow, error)
	GetPentesterProjectsDueThisWeek(ctx context.Context, assignedTo uuid.NullUUID) (int64, error)
	// Get pentester's projects for task creation dropdown
	GetPentesterProjectsForDropdown(ctx context.Context, assignedTo uuid.NullUUID) ([]GetPentesterProjectsForDropdownRow, error)
	// Pentester Submit Report Queries
	// UC22: Get projects for dropdown (assigned to pentester)
	GetPentesterProjectsForReportDropdown(ctx context.Context, assignedTo uuid.NullUUID) ([]GetPentesterProjectsForReportDropdownRow, error)
	GetPentesterRecentVulnerabilities(ctx context.Context, arg GetPentesterRecentVulnerabilitiesParams) ([]GetPentesterRecentVulnerabilitiesRow, error)
	// UC31: Get report details by ID
	GetPentesterReportDetails(ctx context.Context, arg GetPentesterReportDetailsParams) (GetPentesterReportDetailsRow, error)
	GetPentesterReportsPendingReview(ctx context.Context, submittedBy uuid.NullUUID) (int64, error)
	GetPentesterReportsSubmittedCount(ctx context.Context, submittedBy uuid.NullUUID) (int64, error)
	// UC27: Get submitted reports history (with pagination)
	GetPentesterSubmittedReports(ctx context.Context, arg GetPentesterSubmittedReportsParams) ([]GetPentesterSubmittedReportsRow, error)
	// UC16: Fetch and Display Task Board
	GetPentesterTaskBoard(ctx context.Context, assignedTo uuid.NullUUID) ([]GetPentesterTaskBoardRow, error)
	// Get single task by ID for pentester
	GetPentesterTaskByID(ctx context.Context, arg GetPentesterTaskByIDParams) (GetPentesterTaskByIDRow, error)
	// Get tasks by status for pentester (for task board columns)
	GetPentesterTasksByStatus(ctx context.Context, arg GetPentesterTasksByStatusParams) ([]GetPentesterTasksByStatusRow, error)
	GetPentesterUpcomingDeadlines(ctx context.Context, assignedTo uuid.NullUUID) ([]GetPentesterUpcomingDeadlinesRow, error)
	GetPentesterVulnerabilitiesFoundCount(ctx context.Context, discoveredBy uuid.NullUUID) (int64, error)
	GetPentesters(ctx context.Context) ([]GetPentestersRow, error)
	// UC12: Display Project Assets List
	GetProjectAssets(ctx context.Context, projectID uuid.NullUUID) ([]GetProjectAssetsRow, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectByName(ctx context.Context, name string) (Project, error)
	// UC13: Display Project Requirements List
	GetProjectRequirements(ctx context.Context, projectID uuid.NullUUID) ([]ProjectRequirement, error)
	GetProjectStats(ctx context.Context) (GetProjectStatsRow, error)
	GetProjectStatusDistribution(ctx context.Context) ([]GetProjectStatusDistributionRow, error)
	GetProjectsByPentester(ctx context.Context, assignedTo uuid.NullUUID) ([]GetProjectsByPentesterRow, error)
	GetRecentActivityLogs(ctx context.Context, arg GetRecentActivityLogsParams) ([]ActivityLog, error)
	GetRecentSecurityEvents(ctx context.Context, limit int32) ([]GetRecentSecurityEventsRow, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	// UC30: Get rejected report details for resubmission
	GetRejectedReportForResubmit(ctx context.Context, arg GetRejectedReportForResubmitParams) (GetRejectedReportForResubmitRow, error)
	GetRemediationRateCounts(ctx context.Context) (GetRemediationRateCountsRow, error)
	GetRemediationUpdates(ctx context.Context, limit int32) ([]GetRemediationUpdatesRow, error)
	// UC31: Get vulnerability details for a report
	GetReportVulnerabilities(ctx context.Context, reportID uuid.NullUUID) ([]ReportVulnerability, error)
	GetSLABreachAnalysis(ctx context.Context) ([]GetSLABreachAnalysisRow, error)
	GetSLACompliance(ctx context.Context) (GetSLAComplianceRow, error)
	GetSLAComplianceCounts(ctx context.Context) (GetSLAComplianceCountsRow, error)
	GetSecurityMetrics(ctx context.Context) ([]GetSecurityMetricsRow, error)
	GetStakeholderCriticalIssuesCount(ctx context.Context) (int64, error)
	// ============================================================================
	// UC25: Get critical vulnerabilities overdue count
	// ============================================================================
	GetStakeholderCriticalOverdueCount(ctx context.Context) (int64, error)
	// ============================================================================
	// UC11: Get critical vulnerabilities count
	// ============================================================================
	GetStakeholderCriticalVulnerabilitiesCount(ctx context.Context) (int64, error)
	// ============================================================================
	// UC41: Get evidence file by ID for download
	// ============================================================================
	GetStakeholderEvidenceFileByID(ctx context.Context, id uuid.UUID) (GetStakeholderEvidenceFileByIDRow, error)
	// ============================================================================
	// UC26: Get high severity approaching deadline count (within 3 days)
	// ============================================================================
	GetStakeholderHighApproachingDeadlineCount(ctx context.Context) (int64, error)
	// ============================================================================
	// UC12: Get high severity vulnerabilities count
	// ============================================================================
	GetStakeholderHighSeverityVulnerabilitiesCount(ctx context.Context) (int64, error)
	// ============================================================================
	// UC13: Get open issues count (open + in_progress)
	// ============================================================================
	GetStakeholderOpenIssuesCount(ctx context.Context) (int64, error)
	// ============================================================================
	// UC30: Get remediated reports count
	// ============================================================================
	GetStakeholderRemediatedReportsCount(ctx context.Context) (int64, error)
	// ============================================================================
	// UC14: Get remediation count (remediated + verified)
	// ============================================================================
	GetStakeholderRemediationCount(ctx context.Context) (int64, error)
	// ============================================================================
	// UC37: Get report details by ID
	// ============================================================================
	GetStakeholderReportByID(ctx context.Context, id uuid.UUID) (GetStakeholderReportByIDRow, error)
	// ============================================================================
	// UC39: Get evidence files for a report with pagination
	// ============================================================================
	GetStakeholderReportEvidenceFiles(ctx context.Context, arg GetStakeholderReportEvidenceFilesParams) ([]GetStakeholderReportEvidenceFilesRow, error)
	// ============================================================================
	// UC39: Get evidence files count for pagination
	// ============================================================================
	GetStakeholderReportEvidenceFilesCount(ctx context.Context, reportID uuid.NullUUID) (int64, error)
	// ============================================================================
	// UC42: Get report file path for download
	// ============================================================================
	GetStakeholderReportFilePath(ctx context.Context, id uuid.UUID) (sql.NullString, error)
	// ============================================================================
	// UC38: Get vulnerabilities for a report
	// ============================================================================
	GetStakeholderReportVulnerabilities(ctx context.Context, reportID uuid.NullUUID) ([]GetStakeholderReportVulnerabilitiesRow, error)
	// ============================================================================
	// UC32: Get total count for pagination
	// ============================================================================
	GetStakeholderReportsCount(ctx context.Context, status sql.NullString) (int64, error)
	// ============================================================================
	// UC27: Get overall SLA compliance data
	// ============================================================================
	GetStakeholderSLAComplianceData(ctx context.Context) (GetStakeholderSLAComplianceDataRow, error)
	// ============================================================================
	// UC28: Get total reports count
	// ============================================================================
	GetStakeholderTotalReportsCount(ctx context.Context) (int64, error)
	// ============================================================================
	// UC29: Get under review reports count
	// ============================================================================
	GetStakeholderUnderReviewReportsCount(ctx context.Context) (int64, error)
	// ============================================================================
	// UC19: Get total count for pagination
	// ============================================================================
	GetStakeholderVulnerabilitiesCount(ctx context.Context, arg GetStakeholderVulnerabilitiesCountParams) (int64, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	GetTasksByStatus(ctx context.Context, status string) ([]GetTasksByStatusRow, error)
	GetTop5DomainsByVulnerabilities(ctx context.Context) ([]GetTop5DomainsByVulnerabilitiesRow, error)
	GetTotalNotificationsSent(ctx context.Context, createdBy uuid.UUID) (int64, error)
	GetTotalProjectsCount(ctx context.Context) (int64, error)
	GetTotalVulnerabilitiesCount(ctx context.Context) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserForAuth(ctx context.Context, email string) (User, error)
	GetUserStats(ctx context.Context) (GetUserStatsRow, error)
	GetUsersByRole(ctx context.Context, role string) ([]GetUsersByRoleRow, error)
	GetVulnerabilitiesBySeverity(ctx context.Context) ([]GetVulnerabilitiesBySeverityRow, error)
	GetVulnerabilitiesForSecurityScore(ctx context.Context) ([]GetVulnerabilitiesForSecurityScoreRow, error)
	GetVulnerabilityByID(ctx context.Context, id uuid.UUID) (Vulnerability, error)
	GetVulnerabilityStats(ctx context.Context) (GetVulnerabilityStatsRow, error)
	GetVulnerabilityTrendByMonth(ctx context.Context) ([]GetVulnerabilityTrendByMonthRow, error)
	IncrementFailedLoginAttempts(ctx context.Context, id uuid.UUID) error
	ListAllTasks(ctx context.Context) ([]ListAllTasksRow, error)
	ListAllUsersForExport(ctx context.Context) ([]ListAllUsersForExportRow, error)
	ListDomains(ctx context.Context, arg ListDomainsParams) ([]ListDomainsRow, error)
	ListImportantAlerts(ctx context.Context, arg ListImportantAlertsParams) ([]ListImportantAlertsRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	// ============================================================================
	// UC32: List reports with status filter and pagination
	// ============================================================================
	ListStakeholderReports(ctx context.Context, arg ListStakeholderReportsParams) ([]ListStakeholderReportsRow, error)
	// ============================================================================
	// UC19: List vulnerabilities with search, filters, and pagination
	// ============================================================================
	ListStakeholderVulnerabilities(ctx context.Context, arg ListStakeholderVulnerabilitiesParams) ([]ListStakeholderVulnerabilitiesRow, error)
	ListTasksByProject(ctx context.Context, projectID uuid.NullUUID) ([]ListTasksByProjectRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListVulnerabilities(ctx context.Context, arg ListVulnerabilitiesParams) ([]Vulnerability, error)
	LockAccount(ctx context.Context, arg LockAccountParams) error
	// UC36: Mark alert as read
	MarkAlertAsRead(ctx context.Context, arg MarkAlertAsReadParams) error
	// UC36: Mark alert as unread
	MarkAlertAsUnread(ctx context.Context, arg MarkAlertAsUnreadParams) error
	ResetFailedLoginAttempts(ctx context.Context, id uuid.UUID) error
	SearchAndFilterVulnerabilities(ctx context.Context, arg SearchAndFilterVulnerabilitiesParams) ([]Vulnerability, error)
	UnlockAccount(ctx context.Context, id uuid.UUID) error
	UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error)
	UpdateLastLoginTime(ctx context.Context, arg UpdateLastLoginTimeParams) error
	// UC19: Edit Task Details
	UpdatePentesterTask(ctx context.Context, arg UpdatePentesterTaskParams) (Task, error)
	// UC18: Update Task Status
	UpdatePentesterTaskStatus(ctx context.Context, arg UpdatePentesterTaskStatusParams) error
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	UpdateUserForcePasswordChange(ctx context.Context, arg UpdateUserForcePasswordChangeParams) error
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVulnerability(ctx context.Context, arg UpdateVulnerabilityParams) (Vulnerability, error)
}

var _ Querier = (*Queries)(nil)
