// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stakeholder_overview.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const GetActiveProjectsCounts = `-- name: GetActiveProjectsCounts :one
SELECT 
    COUNT(*) FILTER (WHERE status IN ('open', 'in_progress')) AS total_active,
    COUNT(*) FILTER (WHERE status = 'in_progress') AS in_progress,
    COUNT(*) FILTER (WHERE status = 'completed') AS completed
FROM projects
`

type GetActiveProjectsCountsRow struct {
	TotalActive int64 `json:"total_active"`
	InProgress  int64 `json:"in_progress"`
	Completed   int64 `json:"completed"`
}

func (q *Queries) GetActiveProjectsCounts(ctx context.Context) (GetActiveProjectsCountsRow, error) {
	row := q.db.QueryRowContext(ctx, GetActiveProjectsCounts)
	var i GetActiveProjectsCountsRow
	err := row.Scan(&i.TotalActive, &i.InProgress, &i.Completed)
	return i, err
}

const GetAssetVulnerabilityCounts = `-- name: GetAssetVulnerabilityCounts :many
SELECT 
    domain AS asset_name,
    COUNT(*) FILTER (WHERE severity = 'critical') AS critical,
    COUNT(*) FILTER (WHERE severity = 'high') AS high,
    COUNT(*) FILTER (WHERE severity = 'medium') AS medium,
    COUNT(*) FILTER (WHERE severity = 'low') AS low
FROM vulnerabilities
GROUP BY domain
ORDER BY critical DESC, high DESC, medium DESC, low DESC
LIMIT 10
`

type GetAssetVulnerabilityCountsRow struct {
	AssetName string `json:"asset_name"`
	Critical  int64  `json:"critical"`
	High      int64  `json:"high"`
	Medium    int64  `json:"medium"`
	Low       int64  `json:"low"`
}

func (q *Queries) GetAssetVulnerabilityCounts(ctx context.Context) ([]GetAssetVulnerabilityCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetAssetVulnerabilityCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssetVulnerabilityCountsRow{}
	for rows.Next() {
		var i GetAssetVulnerabilityCountsRow
		if err := rows.Scan(
			&i.AssetName,
			&i.Critical,
			&i.High,
			&i.Medium,
			&i.Low,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetOpenVulnerabilitiesCurrentMonth = `-- name: GetOpenVulnerabilitiesCurrentMonth :one
SELECT COUNT(*) AS count
FROM vulnerabilities
WHERE status = 'open'
`

func (q *Queries) GetOpenVulnerabilitiesCurrentMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetOpenVulnerabilitiesCurrentMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetOpenVulnerabilitiesLastMonth = `-- name: GetOpenVulnerabilitiesLastMonth :one
SELECT COUNT(*) AS count
FROM vulnerabilities
WHERE status = 'open'
  AND created_at < DATE_TRUNC('month', CURRENT_DATE)
`

func (q *Queries) GetOpenVulnerabilitiesLastMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetOpenVulnerabilitiesLastMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetRecentSecurityEvents = `-- name: GetRecentSecurityEvents :many
SELECT 
    id,
    action AS description,
    entity_type AS event_type,
    created_at
FROM activity_logs
ORDER BY created_at DESC
LIMIT $1
`

type GetRecentSecurityEventsRow struct {
	ID          uuid.UUID      `json:"id"`
	Description string         `json:"description"`
	EventType   sql.NullString `json:"event_type"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

func (q *Queries) GetRecentSecurityEvents(ctx context.Context, limit int32) ([]GetRecentSecurityEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetRecentSecurityEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentSecurityEventsRow{}
	for rows.Next() {
		var i GetRecentSecurityEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.EventType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRemediationRateCounts = `-- name: GetRemediationRateCounts :one
SELECT 
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE status IN ('remediated', 'verified')) AS remediated
FROM vulnerabilities
`

type GetRemediationRateCountsRow struct {
	Total      int64 `json:"total"`
	Remediated int64 `json:"remediated"`
}

func (q *Queries) GetRemediationRateCounts(ctx context.Context) (GetRemediationRateCountsRow, error) {
	row := q.db.QueryRowContext(ctx, GetRemediationRateCounts)
	var i GetRemediationRateCountsRow
	err := row.Scan(&i.Total, &i.Remediated)
	return i, err
}

const GetRemediationUpdates = `-- name: GetRemediationUpdates :many
SELECT 
    v.id,
    v.title AS vuln_title,
    'open' AS previous_status,
    v.status AS new_status,
    v.remediated_date,
    COALESCE(u.full_name, v.assigned_to, 'Unassigned') AS assigned_team
FROM vulnerabilities v
LEFT JOIN users u ON v.discovered_by = u.id
WHERE v.status IN ('remediated', 'verified')
  AND v.remediated_date IS NOT NULL
ORDER BY v.remediated_date DESC
LIMIT $1
`

type GetRemediationUpdatesRow struct {
	ID             uuid.UUID    `json:"id"`
	VulnTitle      string       `json:"vuln_title"`
	PreviousStatus string       `json:"previous_status"`
	NewStatus      string       `json:"new_status"`
	RemediatedDate sql.NullTime `json:"remediated_date"`
	AssignedTeam   string       `json:"assigned_team"`
}

func (q *Queries) GetRemediationUpdates(ctx context.Context, limit int32) ([]GetRemediationUpdatesRow, error) {
	rows, err := q.db.QueryContext(ctx, GetRemediationUpdates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRemediationUpdatesRow{}
	for rows.Next() {
		var i GetRemediationUpdatesRow
		if err := rows.Scan(
			&i.ID,
			&i.VulnTitle,
			&i.PreviousStatus,
			&i.NewStatus,
			&i.RemediatedDate,
			&i.AssignedTeam,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSLAComplianceCounts = `-- name: GetSLAComplianceCounts :one
SELECT 
    COUNT(*) FILTER (WHERE due_date IS NOT NULL) AS total_with_due_date,
    COUNT(*) FILTER (WHERE due_date IS NOT NULL AND status IN ('remediated', 'verified') AND remediated_date <= due_date) AS remediated_on_time
FROM vulnerabilities
`

type GetSLAComplianceCountsRow struct {
	TotalWithDueDate int64 `json:"total_with_due_date"`
	RemediatedOnTime int64 `json:"remediated_on_time"`
}

func (q *Queries) GetSLAComplianceCounts(ctx context.Context) (GetSLAComplianceCountsRow, error) {
	row := q.db.QueryRowContext(ctx, GetSLAComplianceCounts)
	var i GetSLAComplianceCountsRow
	err := row.Scan(&i.TotalWithDueDate, &i.RemediatedOnTime)
	return i, err
}

const GetStakeholderCriticalIssuesCount = `-- name: GetStakeholderCriticalIssuesCount :one
SELECT COUNT(*) AS count
FROM vulnerabilities
WHERE severity = 'critical'
`

func (q *Queries) GetStakeholderCriticalIssuesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderCriticalIssuesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetVulnerabilitiesForSecurityScore = `-- name: GetVulnerabilitiesForSecurityScore :many
SELECT severity, status
FROM vulnerabilities
`

type GetVulnerabilitiesForSecurityScoreRow struct {
	Severity string `json:"severity"`
	Status   string `json:"status"`
}

func (q *Queries) GetVulnerabilitiesForSecurityScore(ctx context.Context) ([]GetVulnerabilitiesForSecurityScoreRow, error) {
	rows, err := q.db.QueryContext(ctx, GetVulnerabilitiesForSecurityScore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVulnerabilitiesForSecurityScoreRow{}
	for rows.Next() {
		var i GetVulnerabilitiesForSecurityScoreRow
		if err := rows.Scan(&i.Severity, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetVulnerabilityTrendByMonth = `-- name: GetVulnerabilityTrendByMonth :many
SELECT
    EXTRACT(EPOCH FROM DATE_TRUNC('month', created_at))::BIGINT AS month,
    COUNT(*) FILTER (WHERE status = 'open') AS open_count,
    COUNT(*) FILTER (WHERE status IN ('remediated', 'verified')) AS resolved_count
FROM vulnerabilities
WHERE created_at >= DATE_TRUNC('month', CURRENT_DATE) - INTERVAL '5 months'
GROUP BY DATE_TRUNC('month', created_at)
ORDER BY DATE_TRUNC('month', created_at) ASC
`

type GetVulnerabilityTrendByMonthRow struct {
	Month         int64 `json:"month"`
	OpenCount     int64 `json:"open_count"`
	ResolvedCount int64 `json:"resolved_count"`
}

func (q *Queries) GetVulnerabilityTrendByMonth(ctx context.Context) ([]GetVulnerabilityTrendByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, GetVulnerabilityTrendByMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVulnerabilityTrendByMonthRow{}
	for rows.Next() {
		var i GetVulnerabilityTrendByMonthRow
		if err := rows.Scan(&i.Month, &i.OpenCount, &i.ResolvedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
