// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stakeholder_vulnerabilities.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const ExportStakeholderVulnerabilities = `-- name: ExportStakeholderVulnerabilities :many
SELECT 
    id,
    title,
    severity,
    domain,
    status,
    created_at AS discovered_date,
    due_date,
    assigned_to
FROM vulnerabilities
WHERE 
    ($1::TEXT IS NULL OR 
     title ILIKE '%' || $1::TEXT || '%' OR 
     domain ILIKE '%' || $1::TEXT || '%')
    AND ($2::TEXT IS NULL OR $2::TEXT = 'all' OR severity = $2::TEXT)
    AND ($3::TEXT IS NULL OR $3::TEXT = 'all' OR status = $3::TEXT)
ORDER BY created_at DESC
`

type ExportStakeholderVulnerabilitiesParams struct {
	Search   sql.NullString `json:"search"`
	Severity sql.NullString `json:"severity"`
	Status   sql.NullString `json:"status"`
}

type ExportStakeholderVulnerabilitiesRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	Severity       string         `json:"severity"`
	Domain         string         `json:"domain"`
	Status         string         `json:"status"`
	DiscoveredDate sql.NullTime   `json:"discovered_date"`
	DueDate        time.Time      `json:"due_date"`
	AssignedTo     sql.NullString `json:"assigned_to"`
}

// ============================================================================
// UC24: Export vulnerabilities to CSV (all matching filters)
// ============================================================================
func (q *Queries) ExportStakeholderVulnerabilities(ctx context.Context, arg ExportStakeholderVulnerabilitiesParams) ([]ExportStakeholderVulnerabilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, ExportStakeholderVulnerabilities, arg.Search, arg.Severity, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportStakeholderVulnerabilitiesRow{}
	for rows.Next() {
		var i ExportStakeholderVulnerabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Domain,
			&i.Status,
			&i.DiscoveredDate,
			&i.DueDate,
			&i.AssignedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetStakeholderCriticalOverdueCount = `-- name: GetStakeholderCriticalOverdueCount :one
SELECT COUNT(*) AS count
FROM vulnerabilities
WHERE severity = 'critical'
  AND status IN ('open', 'in_progress')
  AND due_date IS NOT NULL
  AND due_date < CURRENT_DATE
`

// ============================================================================
// UC25: Get critical vulnerabilities overdue count
// ============================================================================
func (q *Queries) GetStakeholderCriticalOverdueCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderCriticalOverdueCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetStakeholderCriticalVulnerabilitiesCount = `-- name: GetStakeholderCriticalVulnerabilitiesCount :one
SELECT COUNT(*) AS count
FROM vulnerabilities
WHERE severity = 'critical'
`

// ============================================================================
// UC11: Get critical vulnerabilities count
// ============================================================================
func (q *Queries) GetStakeholderCriticalVulnerabilitiesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderCriticalVulnerabilitiesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetStakeholderHighApproachingDeadlineCount = `-- name: GetStakeholderHighApproachingDeadlineCount :one
SELECT COUNT(*) AS count
FROM vulnerabilities
WHERE severity = 'high'
  AND status IN ('open', 'in_progress')
  AND due_date IS NOT NULL
  AND due_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '3 days'
`

// ============================================================================
// UC26: Get high severity approaching deadline count (within 3 days)
// ============================================================================
func (q *Queries) GetStakeholderHighApproachingDeadlineCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderHighApproachingDeadlineCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetStakeholderHighSeverityVulnerabilitiesCount = `-- name: GetStakeholderHighSeverityVulnerabilitiesCount :one
SELECT COUNT(*) AS count
FROM vulnerabilities
WHERE severity = 'high'
`

// ============================================================================
// UC12: Get high severity vulnerabilities count
// ============================================================================
func (q *Queries) GetStakeholderHighSeverityVulnerabilitiesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderHighSeverityVulnerabilitiesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetStakeholderOpenIssuesCount = `-- name: GetStakeholderOpenIssuesCount :one
SELECT COUNT(*) AS count
FROM vulnerabilities
WHERE status IN ('open', 'in_progress')
`

// ============================================================================
// UC13: Get open issues count (open + in_progress)
// ============================================================================
func (q *Queries) GetStakeholderOpenIssuesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderOpenIssuesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetStakeholderRemediationCount = `-- name: GetStakeholderRemediationCount :one
SELECT COUNT(*) AS count
FROM vulnerabilities
WHERE status IN ('remediated', 'verified')
`

// ============================================================================
// UC14: Get remediation count (remediated + verified)
// ============================================================================
func (q *Queries) GetStakeholderRemediationCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderRemediationCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetStakeholderSLAComplianceData = `-- name: GetStakeholderSLAComplianceData :one
SELECT 
    COUNT(*) FILTER (WHERE due_date IS NOT NULL) AS total_with_due_date,
    COUNT(*) FILTER (WHERE due_date IS NOT NULL AND status IN ('remediated', 'verified') AND remediated_date <= due_date) AS remediated_on_time
FROM vulnerabilities
`

type GetStakeholderSLAComplianceDataRow struct {
	TotalWithDueDate int64 `json:"total_with_due_date"`
	RemediatedOnTime int64 `json:"remediated_on_time"`
}

// ============================================================================
// UC27: Get overall SLA compliance data
// ============================================================================
func (q *Queries) GetStakeholderSLAComplianceData(ctx context.Context) (GetStakeholderSLAComplianceDataRow, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderSLAComplianceData)
	var i GetStakeholderSLAComplianceDataRow
	err := row.Scan(&i.TotalWithDueDate, &i.RemediatedOnTime)
	return i, err
}

const GetStakeholderVulnerabilitiesCount = `-- name: GetStakeholderVulnerabilitiesCount :one
SELECT COUNT(*) AS count
FROM vulnerabilities
WHERE 
    ($1::TEXT IS NULL OR 
     title ILIKE '%' || $1::TEXT || '%' OR 
     domain ILIKE '%' || $1::TEXT || '%')
    AND ($2::TEXT IS NULL OR $2::TEXT = 'all' OR severity = $2::TEXT)
    AND ($3::TEXT IS NULL OR $3::TEXT = 'all' OR status = $3::TEXT)
`

type GetStakeholderVulnerabilitiesCountParams struct {
	Search   sql.NullString `json:"search"`
	Severity sql.NullString `json:"severity"`
	Status   sql.NullString `json:"status"`
}

// ============================================================================
// UC19: Get total count for pagination
// ============================================================================
func (q *Queries) GetStakeholderVulnerabilitiesCount(ctx context.Context, arg GetStakeholderVulnerabilitiesCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderVulnerabilitiesCount, arg.Search, arg.Severity, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ListStakeholderVulnerabilities = `-- name: ListStakeholderVulnerabilities :many
SELECT 
    id,
    title,
    severity,
    domain,
    status,
    created_at AS discovered_date,
    due_date,
    assigned_to
FROM vulnerabilities
WHERE 
    ($3::TEXT IS NULL OR 
     title ILIKE '%' || $3::TEXT || '%' OR 
     domain ILIKE '%' || $3::TEXT || '%')
    AND ($4::TEXT IS NULL OR $4::TEXT = 'all' OR severity = $4::TEXT)
    AND ($5::TEXT IS NULL OR $5::TEXT = 'all' OR status = $5::TEXT)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListStakeholderVulnerabilitiesParams struct {
	Limit    int32          `json:"limit"`
	Offset   int32          `json:"offset"`
	Search   sql.NullString `json:"search"`
	Severity sql.NullString `json:"severity"`
	Status   sql.NullString `json:"status"`
}

type ListStakeholderVulnerabilitiesRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	Severity       string         `json:"severity"`
	Domain         string         `json:"domain"`
	Status         string         `json:"status"`
	DiscoveredDate sql.NullTime   `json:"discovered_date"`
	DueDate        time.Time      `json:"due_date"`
	AssignedTo     sql.NullString `json:"assigned_to"`
}

// ============================================================================
// UC19: List vulnerabilities with search, filters, and pagination
// ============================================================================
func (q *Queries) ListStakeholderVulnerabilities(ctx context.Context, arg ListStakeholderVulnerabilitiesParams) ([]ListStakeholderVulnerabilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, ListStakeholderVulnerabilities,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Severity,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStakeholderVulnerabilitiesRow{}
	for rows.Next() {
		var i ListStakeholderVulnerabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Domain,
			&i.Status,
			&i.DiscoveredDate,
			&i.DueDate,
			&i.AssignedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
