// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stakeholder_reports.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const GetStakeholderEvidenceFileByID = `-- name: GetStakeholderEvidenceFileByID :one
SELECT 
    id,
    file_name,
    file_size,
    created_at AS upload_date,
    file_path
FROM evidence_files
WHERE id = $1
`

type GetStakeholderEvidenceFileByIDRow struct {
	ID         uuid.UUID    `json:"id"`
	FileName   string       `json:"file_name"`
	FileSize   int64        `json:"file_size"`
	UploadDate sql.NullTime `json:"upload_date"`
	FilePath   string       `json:"file_path"`
}

// ============================================================================
// UC41: Get evidence file by ID for download
// ============================================================================
func (q *Queries) GetStakeholderEvidenceFileByID(ctx context.Context, id uuid.UUID) (GetStakeholderEvidenceFileByIDRow, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderEvidenceFileByID, id)
	var i GetStakeholderEvidenceFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.FileName,
		&i.FileSize,
		&i.UploadDate,
		&i.FilePath,
	)
	return i, err
}

const GetStakeholderRemediatedReportsCount = `-- name: GetStakeholderRemediatedReportsCount :one
SELECT COUNT(*) AS count
FROM reports
WHERE status = 'remediated'
`

// ============================================================================
// UC30: Get remediated reports count
// ============================================================================
func (q *Queries) GetStakeholderRemediatedReportsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderRemediatedReportsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetStakeholderReportByID = `-- name: GetStakeholderReportByID :one
SELECT 
    r.id,
    r.title,
    u.full_name AS submitted_by,
    r.created_at AS submission_date,
    p.name AS project_name,
    r.status,
    r.executive_summary
FROM reports r
LEFT JOIN users u ON r.submitted_by = u.id
LEFT JOIN projects p ON r.project_id = p.id
WHERE r.id = $1
`

type GetStakeholderReportByIDRow struct {
	ID               uuid.UUID      `json:"id"`
	Title            string         `json:"title"`
	SubmittedBy      sql.NullString `json:"submitted_by"`
	SubmissionDate   sql.NullTime   `json:"submission_date"`
	ProjectName      sql.NullString `json:"project_name"`
	Status           sql.NullString `json:"status"`
	ExecutiveSummary sql.NullString `json:"executive_summary"`
}

// ============================================================================
// UC37: Get report details by ID
// ============================================================================
func (q *Queries) GetStakeholderReportByID(ctx context.Context, id uuid.UUID) (GetStakeholderReportByIDRow, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderReportByID, id)
	var i GetStakeholderReportByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SubmittedBy,
		&i.SubmissionDate,
		&i.ProjectName,
		&i.Status,
		&i.ExecutiveSummary,
	)
	return i, err
}

const GetStakeholderReportEvidenceFiles = `-- name: GetStakeholderReportEvidenceFiles :many
SELECT 
    id,
    file_name,
    file_size,
    created_at AS upload_date,
    file_path
FROM evidence_files
WHERE report_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetStakeholderReportEvidenceFilesParams struct {
	ReportID uuid.NullUUID `json:"report_id"`
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
}

type GetStakeholderReportEvidenceFilesRow struct {
	ID         uuid.UUID    `json:"id"`
	FileName   string       `json:"file_name"`
	FileSize   int64        `json:"file_size"`
	UploadDate sql.NullTime `json:"upload_date"`
	FilePath   string       `json:"file_path"`
}

// ============================================================================
// UC39: Get evidence files for a report with pagination
// ============================================================================
func (q *Queries) GetStakeholderReportEvidenceFiles(ctx context.Context, arg GetStakeholderReportEvidenceFilesParams) ([]GetStakeholderReportEvidenceFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, GetStakeholderReportEvidenceFiles, arg.ReportID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStakeholderReportEvidenceFilesRow{}
	for rows.Next() {
		var i GetStakeholderReportEvidenceFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileSize,
			&i.UploadDate,
			&i.FilePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetStakeholderReportEvidenceFilesCount = `-- name: GetStakeholderReportEvidenceFilesCount :one
SELECT COUNT(*) AS count
FROM evidence_files
WHERE report_id = $1
`

// ============================================================================
// UC39: Get evidence files count for pagination
// ============================================================================
func (q *Queries) GetStakeholderReportEvidenceFilesCount(ctx context.Context, reportID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderReportEvidenceFilesCount, reportID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetStakeholderReportFilePath = `-- name: GetStakeholderReportFilePath :one
SELECT file_path
FROM reports
WHERE id = $1
`

// ============================================================================
// UC42: Get report file path for download
// ============================================================================
func (q *Queries) GetStakeholderReportFilePath(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderReportFilePath, id)
	var file_path sql.NullString
	err := row.Scan(&file_path)
	return file_path, err
}

const GetStakeholderReportVulnerabilities = `-- name: GetStakeholderReportVulnerabilities :many
SELECT 
    rv.id,
    rv.vulnerability_title AS title,
    rv.severity,
    rv.asset_target AS domain,
    'open' AS status,
    rv.vulnerability_description AS description,
    rv.remediation_recommendation AS remediation
FROM report_vulnerabilities rv
WHERE rv.report_id = $1
ORDER BY 
    CASE rv.severity
        WHEN 'critical' THEN 1
        WHEN 'high' THEN 2
        WHEN 'medium' THEN 3
        WHEN 'low' THEN 4
    END,
    rv.created_at DESC
`

type GetStakeholderReportVulnerabilitiesRow struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Severity    string         `json:"severity"`
	Domain      string         `json:"domain"`
	Status      string         `json:"status"`
	Description string         `json:"description"`
	Remediation sql.NullString `json:"remediation"`
}

// ============================================================================
// UC38: Get vulnerabilities for a report
// ============================================================================
func (q *Queries) GetStakeholderReportVulnerabilities(ctx context.Context, reportID uuid.NullUUID) ([]GetStakeholderReportVulnerabilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, GetStakeholderReportVulnerabilities, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStakeholderReportVulnerabilitiesRow{}
	for rows.Next() {
		var i GetStakeholderReportVulnerabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Domain,
			&i.Status,
			&i.Description,
			&i.Remediation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetStakeholderReportsCount = `-- name: GetStakeholderReportsCount :one
SELECT COUNT(*) AS count
FROM reports r
WHERE 
    ($1::TEXT IS NULL OR $1::TEXT = 'all' OR r.status = $1::TEXT)
`

// ============================================================================
// UC32: Get total count for pagination
// ============================================================================
func (q *Queries) GetStakeholderReportsCount(ctx context.Context, status sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderReportsCount, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetStakeholderTotalReportsCount = `-- name: GetStakeholderTotalReportsCount :one
SELECT COUNT(*) AS count
FROM reports
`

// ============================================================================
// UC28: Get total reports count
// ============================================================================
func (q *Queries) GetStakeholderTotalReportsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderTotalReportsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const GetStakeholderUnderReviewReportsCount = `-- name: GetStakeholderUnderReviewReportsCount :one
SELECT COUNT(*) AS count
FROM reports
WHERE status = 'under_review'
`

// ============================================================================
// UC29: Get under review reports count
// ============================================================================
func (q *Queries) GetStakeholderUnderReviewReportsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, GetStakeholderUnderReviewReportsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ListStakeholderReports = `-- name: ListStakeholderReports :many
SELECT 
    r.id,
    r.title,
    u.full_name AS submitted_by,
    r.created_at AS submitted_date,
    p.name AS project_name,
    r.status,
    (SELECT COUNT(*) FROM report_vulnerabilities rv WHERE rv.report_id = r.id) AS vulnerabilities_count,
    (SELECT COUNT(*) FROM evidence_files ef WHERE ef.report_id = r.id) AS evidence_count
FROM reports r
LEFT JOIN users u ON r.submitted_by = u.id
LEFT JOIN projects p ON r.project_id = p.id
WHERE 
    ($3::TEXT IS NULL OR $3::TEXT = 'all' OR r.status = $3::TEXT)
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListStakeholderReportsParams struct {
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
	Status sql.NullString `json:"status"`
}

type ListStakeholderReportsRow struct {
	ID                   uuid.UUID      `json:"id"`
	Title                string         `json:"title"`
	SubmittedBy          sql.NullString `json:"submitted_by"`
	SubmittedDate        sql.NullTime   `json:"submitted_date"`
	ProjectName          sql.NullString `json:"project_name"`
	Status               sql.NullString `json:"status"`
	VulnerabilitiesCount int64          `json:"vulnerabilities_count"`
	EvidenceCount        int64          `json:"evidence_count"`
}

// ============================================================================
// UC32: List reports with status filter and pagination
// ============================================================================
func (q *Queries) ListStakeholderReports(ctx context.Context, arg ListStakeholderReportsParams) ([]ListStakeholderReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListStakeholderReports, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStakeholderReportsRow{}
	for rows.Next() {
		var i ListStakeholderReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SubmittedBy,
			&i.SubmittedDate,
			&i.ProjectName,
			&i.Status,
			&i.VulnerabilitiesCount,
			&i.EvidenceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
