// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const CountTasksByProject = `-- name: CountTasksByProject :one
SELECT COUNT(*) FROM tasks
WHERE project_id = $1
`

func (q *Queries) CountTasksByProject(ctx context.Context, projectID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountTasksByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id,
    project_id,
    title,
    description,
    status,
    priority,
    assigned_to,
    deadline,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, project_id, title, description, status, priority, assigned_to, deadline, completed_at, created_at, updated_at
`

type CreateTaskParams struct {
	ID          uuid.UUID      `json:"id"`
	ProjectID   uuid.NullUUID  `json:"project_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    sql.NullString `json:"priority"`
	AssignedTo  uuid.NullUUID  `json:"assigned_to"`
	Deadline    sql.NullTime   `json:"deadline"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, CreateTask,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssignedTo,
		arg.Deadline,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.Deadline,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteTask, id)
	return err
}

const GetTaskByID = `-- name: GetTaskByID :one
SELECT id, project_id, title, description, status, priority, assigned_to, deadline, completed_at, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, GetTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.Deadline,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetTasksByStatus = `-- name: GetTasksByStatus :many
SELECT 
    t.id, t.project_id, t.title, t.description, t.status, t.priority, t.assigned_to, t.deadline, t.completed_at, t.created_at, t.updated_at,
    u.full_name as assigned_to_name,
    p.name as project_name
FROM tasks t
LEFT JOIN users u ON t.assigned_to = u.id
LEFT JOIN projects p ON t.project_id = p.id
WHERE t.status = $1
ORDER BY t.created_at DESC
`

type GetTasksByStatusRow struct {
	ID             uuid.UUID      `json:"id"`
	ProjectID      uuid.NullUUID  `json:"project_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	Priority       sql.NullString `json:"priority"`
	AssignedTo     uuid.NullUUID  `json:"assigned_to"`
	Deadline       sql.NullTime   `json:"deadline"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	AssignedToName sql.NullString `json:"assigned_to_name"`
	ProjectName    sql.NullString `json:"project_name"`
}

func (q *Queries) GetTasksByStatus(ctx context.Context, status string) ([]GetTasksByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, GetTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTasksByStatusRow{}
	for rows.Next() {
		var i GetTasksByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.Deadline,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignedToName,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListAllTasks = `-- name: ListAllTasks :many
SELECT 
    t.id, t.project_id, t.title, t.description, t.status, t.priority, t.assigned_to, t.deadline, t.completed_at, t.created_at, t.updated_at,
    u.full_name as assigned_to_name,
    p.name as project_name
FROM tasks t
LEFT JOIN users u ON t.assigned_to = u.id
LEFT JOIN projects p ON t.project_id = p.id
ORDER BY t.created_at DESC
`

type ListAllTasksRow struct {
	ID             uuid.UUID      `json:"id"`
	ProjectID      uuid.NullUUID  `json:"project_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	Priority       sql.NullString `json:"priority"`
	AssignedTo     uuid.NullUUID  `json:"assigned_to"`
	Deadline       sql.NullTime   `json:"deadline"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	AssignedToName sql.NullString `json:"assigned_to_name"`
	ProjectName    sql.NullString `json:"project_name"`
}

func (q *Queries) ListAllTasks(ctx context.Context) ([]ListAllTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, ListAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTasksRow{}
	for rows.Next() {
		var i ListAllTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.Deadline,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignedToName,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListTasksByProject = `-- name: ListTasksByProject :many
SELECT 
    t.id, t.project_id, t.title, t.description, t.status, t.priority, t.assigned_to, t.deadline, t.completed_at, t.created_at, t.updated_at,
    u.full_name as assigned_to_name
FROM tasks t
LEFT JOIN users u ON t.assigned_to = u.id
WHERE t.project_id = $1
ORDER BY t.created_at DESC
`

type ListTasksByProjectRow struct {
	ID             uuid.UUID      `json:"id"`
	ProjectID      uuid.NullUUID  `json:"project_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	Status         string         `json:"status"`
	Priority       sql.NullString `json:"priority"`
	AssignedTo     uuid.NullUUID  `json:"assigned_to"`
	Deadline       sql.NullTime   `json:"deadline"`
	CompletedAt    sql.NullTime   `json:"completed_at"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	AssignedToName sql.NullString `json:"assigned_to_name"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, projectID uuid.NullUUID) ([]ListTasksByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, ListTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByProjectRow{}
	for rows.Next() {
		var i ListTasksByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.Deadline,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignedToName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateTask = `-- name: UpdateTask :exec
UPDATE tasks 
SET 
    title = $2,
    description = $3,
    priority = $4,
    assigned_to = $5,
    deadline = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTaskParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Priority    sql.NullString `json:"priority"`
	AssignedTo  uuid.NullUUID  `json:"assigned_to"`
	Deadline    sql.NullTime   `json:"deadline"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.AssignedTo,
		arg.Deadline,
	)
	return err
}

const UpdateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks 
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, UpdateTaskStatus, arg.ID, arg.Status)
	return err
}
