// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const CheckEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, CheckEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const CountInactiveUsers = `-- name: CountInactiveUsers :one
SELECT COUNT(*) FROM users
WHERE is_active = false
`

func (q *Queries) CountInactiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountInactiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users
WHERE role = $1 AND is_active = $2
`

type CountUsersByRoleParams struct {
	Role     string       `json:"role"`
	IsActive sql.NullBool `json:"is_active"`
}

func (q *Queries) CountUsersByRole(ctx context.Context, arg CountUsersByRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountUsersByRole, arg.Role, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    password_hash,
    full_name,
    role,
    is_active,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, email, password_hash, full_name, role, is_active, force_password_change, failed_login_attempts, last_failed_login, account_locked_until, last_login, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	FullName     string       `json:"full_name"`
	Role         string       `json:"role"`
	IsActive     sql.NullBool `json:"is_active"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, CreateUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLogin,
		&i.AccountLockedUntil,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteUser, id)
	return err
}

const GetUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, role, is_active, force_password_change, failed_login_attempts, last_failed_login, account_locked_until, last_login, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, GetUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLogin,
		&i.AccountLockedUntil,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, role, is_active, force_password_change, failed_login_attempts, last_failed_login, account_locked_until, last_login, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, GetUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLogin,
		&i.AccountLockedUntil,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetUserStats = `-- name: GetUserStats :one
SELECT 
    COUNT(*) FILTER (WHERE role = 'pentester' AND is_active = true) as active_pentesters,
    COUNT(*) FILTER (WHERE role = 'stakeholder' AND is_active = true) as active_stakeholders,
    COUNT(*) FILTER (WHERE is_active = false) as inactive_users,
    COUNT(*) as total_users
FROM users
`

type GetUserStatsRow struct {
	ActivePentesters   int64 `json:"active_pentesters"`
	ActiveStakeholders int64 `json:"active_stakeholders"`
	InactiveUsers      int64 `json:"inactive_users"`
	TotalUsers         int64 `json:"total_users"`
}

func (q *Queries) GetUserStats(ctx context.Context) (GetUserStatsRow, error) {
	row := q.db.QueryRowContext(ctx, GetUserStats)
	var i GetUserStatsRow
	err := row.Scan(
		&i.ActivePentesters,
		&i.ActiveStakeholders,
		&i.InactiveUsers,
		&i.TotalUsers,
	)
	return i, err
}

const ListAllUsersForExport = `-- name: ListAllUsersForExport :many
SELECT 
    u.id,
    u.email,
    u.full_name,
    u.role,
    u.is_active,
    u.last_login,
    u.created_at,
    COUNT(DISTINCT CASE 
        WHEN u.role = 'pentester' THEN p.id 
        ELSE NULL 
    END) as project_count
FROM users u
LEFT JOIN projects p ON u.id = p.assigned_to AND u.role = 'pentester'
GROUP BY u.id, u.email, u.full_name, u.role, u.is_active, u.last_login, u.created_at
ORDER BY u.created_at DESC
`

type ListAllUsersForExportRow struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	FullName     string       `json:"full_name"`
	Role         string       `json:"role"`
	IsActive     sql.NullBool `json:"is_active"`
	LastLogin    sql.NullTime `json:"last_login"`
	CreatedAt    sql.NullTime `json:"created_at"`
	ProjectCount int64        `json:"project_count"`
}

func (q *Queries) ListAllUsersForExport(ctx context.Context) ([]ListAllUsersForExportRow, error) {
	rows, err := q.db.QueryContext(ctx, ListAllUsersForExport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllUsersForExportRow{}
	for rows.Next() {
		var i ListAllUsersForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.ProjectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUsers = `-- name: ListUsers :many
SELECT 
    u.id,
    u.email,
    u.full_name,
    u.role,
    u.is_active,
    u.last_login,
    u.created_at,
    u.updated_at,
    COUNT(DISTINCT CASE 
        WHEN u.role = 'pentester' THEN p.id 
        ELSE NULL 
    END) as project_count
FROM users u
LEFT JOIN projects p ON u.id = p.assigned_to AND u.role = 'pentester'
GROUP BY u.id, u.email, u.full_name, u.role, u.is_active, u.last_login, u.created_at, u.updated_at
ORDER BY u.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	FullName     string       `json:"full_name"`
	Role         string       `json:"role"`
	IsActive     sql.NullBool `json:"is_active"`
	LastLogin    sql.NullTime `json:"last_login"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	ProjectCount int64        `json:"project_count"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, ListUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = $1, updated_at = $2
WHERE id = $3
`

type UpdateUserLastLoginParams struct {
	LastLogin sql.NullTime `json:"last_login"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ID        uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, UpdateUserLastLogin, arg.LastLogin, arg.UpdatedAt, arg.ID)
	return err
}
