// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vulnerabilities.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const CountSearchAndFilterVulnerabilities = `-- name: CountSearchAndFilterVulnerabilities :one
SELECT COUNT(*) FROM vulnerabilities
WHERE
    (LOWER(title) LIKE LOWER($1) OR LOWER(domain) LIKE LOWER($1))
    AND ($2 = '' OR severity = $2)
    AND ($3 = '' OR status = $3)
`

type CountSearchAndFilterVulnerabilitiesParams struct {
	Lower   string      `json:"lower"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
}

func (q *Queries) CountSearchAndFilterVulnerabilities(ctx context.Context, arg CountSearchAndFilterVulnerabilitiesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountSearchAndFilterVulnerabilities, arg.Lower, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountVulnerabilities = `-- name: CountVulnerabilities :one
SELECT COUNT(*) FROM vulnerabilities
`

func (q *Queries) CountVulnerabilities(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountVulnerabilities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateVulnerability = `-- name: CreateVulnerability :one
INSERT INTO vulnerabilities (
    id,
    title,
    description,
    severity,
    domain,
    status,
    discovered_date,
    due_date,
    assigned_to,
    cvss_score,
    cwe_id,
    domain_id,
    project_id,
    discovered_by,
    remediation_notes,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
) RETURNING id, title, description, severity, domain, status, discovered_date, due_date, assigned_to, cvss_score, cwe_id, domain_id, project_id, discovered_by, remediation_notes, remediated_date, created_at, updated_at
`

type CreateVulnerabilityParams struct {
	ID               uuid.UUID      `json:"id"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Severity         string         `json:"severity"`
	Domain           string         `json:"domain"`
	Status           string         `json:"status"`
	DiscoveredDate   sql.NullTime   `json:"discovered_date"`
	DueDate          time.Time      `json:"due_date"`
	AssignedTo       sql.NullString `json:"assigned_to"`
	CvssScore        sql.NullString `json:"cvss_score"`
	CweID            sql.NullString `json:"cwe_id"`
	DomainID         uuid.NullUUID  `json:"domain_id"`
	ProjectID        uuid.NullUUID  `json:"project_id"`
	DiscoveredBy     uuid.NullUUID  `json:"discovered_by"`
	RemediationNotes sql.NullString `json:"remediation_notes"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

func (q *Queries) CreateVulnerability(ctx context.Context, arg CreateVulnerabilityParams) (Vulnerability, error) {
	row := q.db.QueryRowContext(ctx, CreateVulnerability,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.Domain,
		arg.Status,
		arg.DiscoveredDate,
		arg.DueDate,
		arg.AssignedTo,
		arg.CvssScore,
		arg.CweID,
		arg.DomainID,
		arg.ProjectID,
		arg.DiscoveredBy,
		arg.RemediationNotes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Vulnerability
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Domain,
		&i.Status,
		&i.DiscoveredDate,
		&i.DueDate,
		&i.AssignedTo,
		&i.CvssScore,
		&i.CweID,
		&i.DomainID,
		&i.ProjectID,
		&i.DiscoveredBy,
		&i.RemediationNotes,
		&i.RemediatedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const DeleteVulnerability = `-- name: DeleteVulnerability :exec
DELETE FROM vulnerabilities
WHERE id = $1
`

func (q *Queries) DeleteVulnerability(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, DeleteVulnerability, id)
	return err
}

const ExportVulnerabilities = `-- name: ExportVulnerabilities :many
SELECT
    id,
    title,
    severity,
    domain,
    status,
    discovered_date,
    due_date,
    assigned_to
FROM vulnerabilities
WHERE
    (LOWER(title) LIKE LOWER($1) OR LOWER(domain) LIKE LOWER($1))
    AND ($2 = '' OR severity = $2)
    AND ($3 = '' OR status = $3)
ORDER BY created_at DESC
`

type ExportVulnerabilitiesParams struct {
	Lower   string      `json:"lower"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
}

type ExportVulnerabilitiesRow struct {
	ID             uuid.UUID      `json:"id"`
	Title          string         `json:"title"`
	Severity       string         `json:"severity"`
	Domain         string         `json:"domain"`
	Status         string         `json:"status"`
	DiscoveredDate sql.NullTime   `json:"discovered_date"`
	DueDate        time.Time      `json:"due_date"`
	AssignedTo     sql.NullString `json:"assigned_to"`
}

func (q *Queries) ExportVulnerabilities(ctx context.Context, arg ExportVulnerabilitiesParams) ([]ExportVulnerabilitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, ExportVulnerabilities, arg.Lower, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportVulnerabilitiesRow{}
	for rows.Next() {
		var i ExportVulnerabilitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.Domain,
			&i.Status,
			&i.DiscoveredDate,
			&i.DueDate,
			&i.AssignedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetSLACompliance = `-- name: GetSLACompliance :one
SELECT
    COUNT(*) FILTER (WHERE severity = 'critical' AND due_date < NOW() AND status NOT IN ('remediated', 'verified')) as critical_overdue,
    COUNT(*) FILTER (WHERE severity = 'high' AND due_date < NOW() + INTERVAL '7 days' AND due_date > NOW() AND status NOT IN ('remediated', 'verified')) as high_approaching,
    COUNT(*) FILTER (WHERE due_date IS NOT NULL) as total_with_due_date,
    COUNT(*) FILTER (WHERE status IN ('remediated', 'verified') AND due_date >= created_at) as remediated_on_time
FROM vulnerabilities
`

type GetSLAComplianceRow struct {
	CriticalOverdue  int64 `json:"critical_overdue"`
	HighApproaching  int64 `json:"high_approaching"`
	TotalWithDueDate int64 `json:"total_with_due_date"`
	RemediatedOnTime int64 `json:"remediated_on_time"`
}

func (q *Queries) GetSLACompliance(ctx context.Context) (GetSLAComplianceRow, error) {
	row := q.db.QueryRowContext(ctx, GetSLACompliance)
	var i GetSLAComplianceRow
	err := row.Scan(
		&i.CriticalOverdue,
		&i.HighApproaching,
		&i.TotalWithDueDate,
		&i.RemediatedOnTime,
	)
	return i, err
}

const GetVulnerabilityByID = `-- name: GetVulnerabilityByID :one
SELECT id, title, description, severity, domain, status, discovered_date, due_date, assigned_to, cvss_score, cwe_id, domain_id, project_id, discovered_by, remediation_notes, remediated_date, created_at, updated_at FROM vulnerabilities
WHERE id = $1
`

func (q *Queries) GetVulnerabilityByID(ctx context.Context, id uuid.UUID) (Vulnerability, error) {
	row := q.db.QueryRowContext(ctx, GetVulnerabilityByID, id)
	var i Vulnerability
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Domain,
		&i.Status,
		&i.DiscoveredDate,
		&i.DueDate,
		&i.AssignedTo,
		&i.CvssScore,
		&i.CweID,
		&i.DomainID,
		&i.ProjectID,
		&i.DiscoveredBy,
		&i.RemediationNotes,
		&i.RemediatedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const GetVulnerabilityStats = `-- name: GetVulnerabilityStats :one
SELECT
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE severity = 'critical') as critical,
    COUNT(*) FILTER (WHERE severity = 'high') as high,
    COUNT(*) FILTER (WHERE severity = 'medium') as medium,
    COUNT(*) FILTER (WHERE severity = 'low') as low,
    COUNT(*) FILTER (WHERE status = 'open') as open,
    COUNT(*) FILTER (WHERE status = 'in_progress') as in_progress,
    COUNT(*) FILTER (WHERE status = 'remediated') as remediated,
    COUNT(*) FILTER (WHERE status = 'verified') as verified
FROM vulnerabilities
`

type GetVulnerabilityStatsRow struct {
	Total      int64 `json:"total"`
	Critical   int64 `json:"critical"`
	High       int64 `json:"high"`
	Medium     int64 `json:"medium"`
	Low        int64 `json:"low"`
	Open       int64 `json:"open"`
	InProgress int64 `json:"in_progress"`
	Remediated int64 `json:"remediated"`
	Verified   int64 `json:"verified"`
}

func (q *Queries) GetVulnerabilityStats(ctx context.Context) (GetVulnerabilityStatsRow, error) {
	row := q.db.QueryRowContext(ctx, GetVulnerabilityStats)
	var i GetVulnerabilityStatsRow
	err := row.Scan(
		&i.Total,
		&i.Critical,
		&i.High,
		&i.Medium,
		&i.Low,
		&i.Open,
		&i.InProgress,
		&i.Remediated,
		&i.Verified,
	)
	return i, err
}

const ListVulnerabilities = `-- name: ListVulnerabilities :many
SELECT id, title, description, severity, domain, status, discovered_date, due_date, assigned_to, cvss_score, cwe_id, domain_id, project_id, discovered_by, remediation_notes, remediated_date, created_at, updated_at FROM vulnerabilities
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListVulnerabilitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVulnerabilities(ctx context.Context, arg ListVulnerabilitiesParams) ([]Vulnerability, error) {
	rows, err := q.db.QueryContext(ctx, ListVulnerabilities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vulnerability{}
	for rows.Next() {
		var i Vulnerability
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.Domain,
			&i.Status,
			&i.DiscoveredDate,
			&i.DueDate,
			&i.AssignedTo,
			&i.CvssScore,
			&i.CweID,
			&i.DomainID,
			&i.ProjectID,
			&i.DiscoveredBy,
			&i.RemediationNotes,
			&i.RemediatedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchAndFilterVulnerabilities = `-- name: SearchAndFilterVulnerabilities :many
SELECT id, title, description, severity, domain, status, discovered_date, due_date, assigned_to, cvss_score, cwe_id, domain_id, project_id, discovered_by, remediation_notes, remediated_date, created_at, updated_at FROM vulnerabilities
WHERE
    (LOWER(title) LIKE LOWER($1) OR LOWER(domain) LIKE LOWER($1))
    AND ($2 = '' OR severity = $2)
    AND ($3 = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type SearchAndFilterVulnerabilitiesParams struct {
	Lower   string      `json:"lower"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) SearchAndFilterVulnerabilities(ctx context.Context, arg SearchAndFilterVulnerabilitiesParams) ([]Vulnerability, error) {
	rows, err := q.db.QueryContext(ctx, SearchAndFilterVulnerabilities,
		arg.Lower,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vulnerability{}
	for rows.Next() {
		var i Vulnerability
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Severity,
			&i.Domain,
			&i.Status,
			&i.DiscoveredDate,
			&i.DueDate,
			&i.AssignedTo,
			&i.CvssScore,
			&i.CweID,
			&i.DomainID,
			&i.ProjectID,
			&i.DiscoveredBy,
			&i.RemediationNotes,
			&i.RemediatedDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateVulnerability = `-- name: UpdateVulnerability :one
UPDATE vulnerabilities
SET
    title = $2,
    description = $3,
    severity = $4,
    domain = $5,
    status = $6,
    discovered_date = $7,
    due_date = $8,
    assigned_to = $9,
    cvss_score = $10,
    cwe_id = $11,
    remediation_notes = $12,
    updated_at = $13
WHERE id = $1
RETURNING id, title, description, severity, domain, status, discovered_date, due_date, assigned_to, cvss_score, cwe_id, domain_id, project_id, discovered_by, remediation_notes, remediated_date, created_at, updated_at
`

type UpdateVulnerabilityParams struct {
	ID               uuid.UUID      `json:"id"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	Severity         string         `json:"severity"`
	Domain           string         `json:"domain"`
	Status           string         `json:"status"`
	DiscoveredDate   sql.NullTime   `json:"discovered_date"`
	DueDate          time.Time      `json:"due_date"`
	AssignedTo       sql.NullString `json:"assigned_to"`
	CvssScore        sql.NullString `json:"cvss_score"`
	CweID            sql.NullString `json:"cwe_id"`
	RemediationNotes sql.NullString `json:"remediation_notes"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

func (q *Queries) UpdateVulnerability(ctx context.Context, arg UpdateVulnerabilityParams) (Vulnerability, error) {
	row := q.db.QueryRowContext(ctx, UpdateVulnerability,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.Domain,
		arg.Status,
		arg.DiscoveredDate,
		arg.DueDate,
		arg.AssignedTo,
		arg.CvssScore,
		arg.CweID,
		arg.RemediationNotes,
		arg.UpdatedAt,
	)
	var i Vulnerability
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Severity,
		&i.Domain,
		&i.Status,
		&i.DiscoveredDate,
		&i.DueDate,
		&i.AssignedTo,
		&i.CvssScore,
		&i.CweID,
		&i.DomainID,
		&i.ProjectID,
		&i.DiscoveredBy,
		&i.RemediationNotes,
		&i.RemediatedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
