package dto

import (
	"time"

	"github.com/google/uuid"
)

// CreateUserRequest represents the request to create a new user
type CreateUserRequest struct {
	FullName string `json:"full_name" validate:"required,min=2,max=255"`
	Email    string `json:"email" validate:"required,email"`
	Role     string `json:"role" validate:"required,oneof=pentester stakeholder"`
}

// CreateUserResponse represents the response after creating a user
type CreateUserResponse struct {
	ID                 uuid.UUID `json:"id"`
	FullName           string    `json:"full_name"`
	Email              string    `json:"email"`
	Role               string    `json:"role"`
	IsActive           bool      `json:"is_active"`
	AutoGeneratedCreds struct {
		Username string `json:"username"`
		Password string `json:"password"`
	} `json:"auto_generated_credentials"`
	CreatedAt time.Time `json:"created_at"`
}

// UserListItem represents a single user in the list
type UserListItem struct {
	ID           uuid.UUID  `json:"id"`
	FullName     string     `json:"full_name"`
	Email        string     `json:"email"`
	Role         string     `json:"role"`
	IsActive     bool       `json:"is_active"`
	ProjectCount int64      `json:"project_count"`
	LastActive   *time.Time `json:"last_active"`
	CreatedAt    time.Time  `json:"created_at"`
}

// ListUsersResponse represents the paginated list of users
type ListUsersResponse struct {
	Users      []UserListItem `json:"users"`
	Pagination PaginationInfo `json:"pagination"`
}

// PaginationInfo represents pagination metadata
type PaginationInfo struct {
	CurrentPage int   `json:"current_page"`
	PerPage     int   `json:"per_page"`
	Total       int64 `json:"total"`
	TotalPages  int   `json:"total_pages"`
	HasNext     bool  `json:"has_next"`
	HasPrev     bool  `json:"has_prev"`
}

// UserStatsResponse represents user statistics
type UserStatsResponse struct {
	ActivePentesters    int64 `json:"active_pentesters"`
	ActiveStakeholders  int64 `json:"active_stakeholders"`
	InactiveUsers       int64 `json:"inactive_users"`
	TotalUsers          int64 `json:"total_users"`
}

// UpdateUserRequest represents the request to update a user
type UpdateUserRequest struct {
	FullName string `json:"full_name" validate:"required,min=2,max=255"`
	Email    string `json:"email" validate:"required,email"`
	Role     string `json:"role" validate:"required,oneof=admin pentester stakeholder"`
	IsActive *bool  `json:"is_active,omitempty"`
}

// UpdateUserResponse represents the response after updating a user
type UpdateUserResponse struct {
	ID        uuid.UUID `json:"id"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	IsActive  bool      `json:"is_active"`
	UpdatedAt time.Time `json:"updated_at"`
}

// DeleteUserRequest represents the request to delete a user
type DeleteUserRequest struct {
	UserID uuid.UUID `json:"user_id" validate:"required"`
}

// ExportUserItem represents a user for CSV export
type ExportUserItem struct {
	FullName     string     `json:"full_name"`
	Email        string     `json:"email"`
	Role         string     `json:"role"`
	Status       string     `json:"status"`
	ProjectCount int64      `json:"project_count"`
	LastActive   *time.Time `json:"last_active"`
}

