package usecases

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/csv"
	"fmt"
	"math/big"
	"strings"
	"time"

	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"github.com/pentsecops/backend/internal/core/domain"
	"github.com/pentsecops/backend/internal/core/domain/dto"
	"github.com/pentsecops/backend/pkg/utils"
	"golang.org/x/crypto/argon2"
)

// UsersUseCase implements the UsersUseCase interface
type UsersUseCase struct {
	repo      domain.UsersRepository
	validator *validator.Validate
}

// NewUsersUseCase creates a new UsersUseCase
func NewUsersUseCase(repo domain.UsersRepository) domain.UsersUseCase {
	return &UsersUseCase{
		repo:      repo,
		validator: validator.New(),
	}
}

// CreateUser creates a new user with auto-generated credentials
// UC14: Create New User with Email and Role
func (uc *UsersUseCase) CreateUser(ctx context.Context, req *dto.CreateUserRequest) (*dto.CreateUserResponse, error) {
	// UC15: Validate Required Fields
	if err := uc.validator.Struct(req); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}

	// UC16: Validate Email Format (already done by validator)

	// Check if email already exists
	exists, err := uc.repo.CheckEmailExists(ctx, req.Email)
	if err != nil {
		fmt.Printf("CheckEmailExists Error: %v\n", err)
		return nil, fmt.Errorf("failed to check email existence: %w", err)
	}
	if exists {
		return nil, fmt.Errorf("email already exists")
	}

	// Generate UUIDv7 for user ID
	userID, err := uuid.NewV7()
	if err != nil {
		return nil, fmt.Errorf("failed to generate user ID: %w", err)
	}

	// Auto-generate credentials
	username := generateUsername(req.Email)
	password := generateSecurePassword(12)
	passwordHash := hashPassword(password)

	// Create user params
	now := time.Now()
	params := &domain.CreateUserParams{
		ID:           userID.String(),
		Email:        req.Email,
		PasswordHash: passwordHash,
		FullName:     req.FullName,
		Role:         req.Role,
		IsActive:     true,
		CreatedAt:    now,
		UpdatedAt:    now,
	}

	// Create user in database
	user, err := uc.repo.CreateUser(ctx, params)
	if err != nil {
		fmt.Printf("CreateUser Repository Error: %v\n", err)
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	// Build response with auto-generated credentials
	response := &dto.CreateUserResponse{
		ID:        user.ID,
		FullName:  user.FullName,
		Email:     user.Email,
		Role:      user.Role,
		IsActive:  user.IsActive,
		CreatedAt: user.CreatedAt,
	}
	response.AutoGeneratedCreds.Username = username
	response.AutoGeneratedCreds.Password = password

	// Send password via email
	go func(email, password string) {
		subject := "Your PentSecOps Account Credentials"
		body := "Hello,\n\nYour account has been created.\n\nUsername: " + username + "\nPassword: " + password + "\n\nPlease log in and change your password immediately.\n\nPentSecOps Team"
		_ = utils.SendEmail(email, subject, body)
	}(req.Email, password)

	return response, nil
}

// ListUsers retrieves a paginated list of users
// UC17: Display All Users with Pagination
func (uc *UsersUseCase) ListUsers(ctx context.Context, page, perPage int) (*dto.ListUsersResponse, error) {
	// Default pagination values
	if page < 1 {
		page = 1
	}
	if perPage < 1 || perPage > 100 {
		perPage = 5 // Default to 5 per page as per requirements
	}

	// Calculate offset
	offset := (page - 1) * perPage

	// Get total count
	totalCount, err := uc.repo.CountUsers(ctx)
	if err != nil {
		fmt.Printf("CountUsers Error: %v\n", err)
		return nil, fmt.Errorf("failed to count users: %w", err)
	}

	// Get users
	users, err := uc.repo.ListUsers(ctx, perPage, offset)
	if err != nil {
		fmt.Printf("ListUsers Error: %v\n", err)
		return nil, fmt.Errorf("failed to list users: %w", err)
	}

	// Convert to DTOs
	userItems := make([]dto.UserListItem, 0, len(users))
	for _, u := range users {
		userID, _ := uuid.Parse(u.ID)
		userItems = append(userItems, dto.UserListItem{
			ID:           userID,
			FullName:     u.FullName,
			Email:        u.Email,
			Role:         u.Role,
			IsActive:     u.IsActive,
			ProjectCount: u.ProjectCount,
			LastActive:   u.LastLogin,
			CreatedAt:    u.CreatedAt,
		})
	}

	// Calculate pagination info
	totalPages := int(totalCount) / perPage
	if int(totalCount)%perPage != 0 {
		totalPages++
	}

	response := &dto.ListUsersResponse{
		Users: userItems,
		Pagination: dto.PaginationInfo{
			CurrentPage: page,
			PerPage:     perPage,
			Total:       totalCount,
			TotalPages:  totalPages,
			HasNext:     page < totalPages,
			HasPrev:     page > 1,
		},
	}

	return response, nil
}

// DeleteUser deletes a user
// UC19: Delete User from Table
func (uc *UsersUseCase) DeleteUser(ctx context.Context, userID string) error {
	// Validate UUID format
	if _, err := uuid.Parse(userID); err != nil {
		return fmt.Errorf("invalid user ID format: %w", err)
	}

	// Delete user
	err := uc.repo.DeleteUser(ctx, userID)
	if err != nil {
		fmt.Printf("DeleteUser Error: %v\n", err)
		return fmt.Errorf("failed to delete user: %w", err)
	}

	return nil
}

// UpdateUser updates an existing user
func (uc *UsersUseCase) UpdateUser(ctx context.Context, userID string, req *dto.UpdateUserRequest) (*dto.UpdateUserResponse, error) {
	// Validate UUID format
	if _, err := uuid.Parse(userID); err != nil {
		return nil, fmt.Errorf("invalid user ID format: %w", err)
	}

	// Validate request
	if err := uc.validator.Struct(req); err != nil {
		return nil, fmt.Errorf("validation failed: %w", err)
	}

	// Check if user exists
	userUUID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID format: %w", err)
	}
	existingUser, err := uc.repo.GetUserByID(ctx, userUUID)
	if err != nil {
		fmt.Printf("GetUserByID Error: %v\n", err)
		return nil, fmt.Errorf("user not found")
	}

	// Check if email is being changed and if it already exists
	if req.Email != existingUser.Email {
		exists, err := uc.repo.CheckEmailExists(ctx, req.Email)
		if err != nil {
			fmt.Printf("CheckEmailExists Error in Update: %v\n", err)
			return nil, fmt.Errorf("failed to check email existence: %w", err)
		}
		if exists {
			return nil, fmt.Errorf("email already exists")
		}
	}

	// Update user
	updatedUser, err := uc.repo.UpdateUser(ctx, userID, &domain.UpdateUserParams{
		FullName: req.FullName,
		Email:    req.Email,
		Role:     req.Role,
		IsActive: req.IsActive,
	})
	if err != nil {
		fmt.Printf("UpdateUser Repository Error: %v\n", err)
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	return &dto.UpdateUserResponse{
		ID:        updatedUser.ID,
		FullName:  updatedUser.FullName,
		Email:     updatedUser.Email,
		Role:      updatedUser.Role,
		IsActive:  updatedUser.IsActive,
		UpdatedAt: updatedUser.UpdatedAt,
	}, nil
}

// RefreshUsers refreshes the user list (same as ListUsers)
// UC12: Refresh Users List
func (uc *UsersUseCase) RefreshUsers(ctx context.Context, page, perPage int) (*dto.ListUsersResponse, error) {
	return uc.ListUsers(ctx, page, perPage)
}

// GetUserStats retrieves user statistics
// UC24: Fetch and Display User Statistics
func (uc *UsersUseCase) GetUserStats(ctx context.Context) (*dto.UserStatsResponse, error) {
	stats, err := uc.repo.GetUserStats(ctx)
	if err != nil {
		fmt.Printf("GetUserStats Error: %v\n", err)
		return nil, fmt.Errorf("failed to get user stats: %w", err)
	}

	return &dto.UserStatsResponse{
		ActivePentesters:   stats.ActivePentesters,
		ActiveStakeholders: stats.ActiveStakeholders,
		InactiveUsers:      stats.InactiveUsers,
		TotalUsers:         stats.TotalUsers,
	}, nil
}

// ExportUsersToCSV exports all users to CSV format
// UC25: Export Users to CSV
func (uc *UsersUseCase) ExportUsersToCSV(ctx context.Context) ([]byte, error) {
	// Get all users
	users, err := uc.repo.ListAllUsersForExport(ctx)
	if err != nil {
		fmt.Printf("ListAllUsersForExport Error: %v\n", err)
		return nil, fmt.Errorf("failed to get users for export: %w", err)
	}

	// Create CSV buffer
	var buf bytes.Buffer
	writer := csv.NewWriter(&buf)

	// Write header
	header := []string{"Name", "Email", "Role", "Status", "Projects", "Last Active"}
	if err := writer.Write(header); err != nil {
		return nil, fmt.Errorf("failed to write CSV header: %w", err)
	}

	// Write data rows
	for _, u := range users {
		status := "Active"
		if !u.IsActive {
			status = "Inactive"
		}

		lastActive := "Never"
		if u.LastLogin != nil {
			lastActive = u.LastLogin.Format("2006-01-02 15:04:05")
		}

		row := []string{
			u.FullName,
			u.Email,
			strings.Title(u.Role),
			status,
			fmt.Sprintf("%d", u.ProjectCount),
			lastActive,
		}

		if err := writer.Write(row); err != nil {
			return nil, fmt.Errorf("failed to write CSV row: %w", err)
		}
	}

	writer.Flush()
	if err := writer.Error(); err != nil {
		return nil, fmt.Errorf("CSV writer error: %w", err)
	}

	return buf.Bytes(), nil
}

// Helper functions

// generateUsername generates a username from email
func generateUsername(email string) string {
	parts := strings.Split(email, "@")
	if len(parts) > 0 {
		return parts[0]
	}
	return email
}

// generateSecurePassword generates a secure random password
func generateSecurePassword(length int) string {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"
	password := make([]byte, length)

	for i := range password {
		num, _ := rand.Int(rand.Reader, big.NewInt(int64(len(charset))))
		password[i] = charset[num.Int64()]
	}

	return string(password)
}

// hashPassword hashes a password using Argon2id
func hashPassword(password string) string {
	// Argon2id parameters
	salt := make([]byte, 16)
	rand.Read(salt)

	hash := argon2.IDKey([]byte(password), salt, 1, 64*1024, 4, 32)

	// Return base64 encoded hash (in production, you'd want to store salt separately)
	return fmt.Sprintf("%x", hash)
}
